modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="jujutsucraft"
version="46.1"
displayName="Jujutsu Craft"
displayURL="https://mcreator.net"
credits="Created using mod maker imgaine - https://imgaine.net/about"
authors="orca, imgaine"
description="Jujutsu Craft Mod"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.jujutsucraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.jujutsucraft]]
    modId="geckolib"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.jujutsucraft]]
    modId="playeranimator"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.jujutsucraft]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.jujutsucraft]]
    modId="playeranimator"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration