package org.imgaine.gaigegaigekaigecraft.init;

import org.imgaine.gaigegaigekaigecraft.potion.AttackingMobEffect;
import org.imgaine.gaigegaigekaigecraft.potion.BrainDamageMobEffect;
import org.imgaine.gaigegaigekaigecraft.potion.CancelCursedTechniqueMobEffect;
import org.imgaine.gaigegaigekaigecraft.potion.ComedianMobEffect;
import org.imgaine.gaigegaigekaigecraft.potion.ConvergenceMobEffect;
import org.imgaine.gaigegaigekaigecraft.potion.CooldownTimeBackStepMobEffect;
import org.imgaine.gaigegaigekaigecraft.potion.CooldownTimeCombatMobEffect;
import org.imgaine.gaigegaigekaigecraft.potion.CooldownTimeGuardMobEffect;
import org.imgaine.gaigegaigekaigecraft.potion.CooldownTimeMobEffect;
import org.imgaine.gaigegaigekaigecraft.potion.CooldownTimeSimpleDomainMobEffect;
import org.imgaine.gaigegaigekaigecraft.potion.CursedPoisonMobEffect;
import org.imgaine.gaigegaigekaigecraft.potion.CursedTechniqueMobEffect;
import org.imgaine.gaigegaigekaigecraft.potion.DamageEffectMobEffect;
import org.imgaine.gaigegaigekaigecraft.potion.DeathPaintingBloodMobEffect;
import org.imgaine.gaigegaigekaigecraft.potion.DeepConcentrationMobEffect;
import org.imgaine.gaigegaigekaigecraft.potion.DomainAmplificationMobEffect;
import org.imgaine.gaigegaigekaigecraft.potion.DomainExpansionMobEffect;
import org.imgaine.gaigegaigekaigecraft.potion.DoubleJumpEffectMobEffect;
import org.imgaine.gaigegaigekaigecraft.potion.EffectInfinityMobEffect;
import org.imgaine.gaigegaigekaigecraft.potion.EffectKirinMobEffect;
import org.imgaine.gaigegaigekaigecraft.potion.EffectReikiMobEffect;
import org.imgaine.gaigegaigekaigecraft.potion.FallingBlossomEmotionMobEffect;
import org.imgaine.gaigegaigekaigecraft.potion.FatigueMobEffect;
import org.imgaine.gaigegaigekaigecraft.potion.FlyEffectMobEffect;
import org.imgaine.gaigegaigekaigecraft.potion.GuardMobEffect;
import org.imgaine.gaigegaigekaigecraft.potion.HighSpeedMobEffect;
import org.imgaine.gaigegaigekaigecraft.potion.IgnoreGuardMobEffect;
import org.imgaine.gaigegaigekaigecraft.potion.InsectArmorTechniqueMobEffect;
import org.imgaine.gaigegaigekaigecraft.potion.InstantSpiritBodyofDistortedKillingEffectMobEffect;
import org.imgaine.gaigegaigekaigecraft.potion.JackpotMobEffect;
import org.imgaine.gaigegaigekaigecraft.potion.MythicalBeastAmberEffectMobEffect;
import org.imgaine.gaigegaigekaigecraft.potion.NeutralizationMobEffect;
import org.imgaine.gaigegaigekaigecraft.potion.PhysicalGiftedEffectMobEffect;
import org.imgaine.gaigegaigekaigecraft.potion.PrayerSongMobEffect;
import org.imgaine.gaigegaigekaigecraft.potion.ProjectionSorceryMobEffect;
import org.imgaine.gaigegaigekaigecraft.potion.ReverseCursedTechniqueMobEffect;
import org.imgaine.gaigegaigekaigecraft.potion.ScaleChangeMobEffect;
import org.imgaine.gaigegaigekaigecraft.potion.SimpleDomainMobEffect;
import org.imgaine.gaigegaigekaigecraft.potion.SixEyesMobEffect;
import org.imgaine.gaigegaigekaigecraft.potion.SpecialMobEffect;
import org.imgaine.gaigegaigekaigecraft.potion.StarRageMobEffect;
import org.imgaine.gaigegaigekaigecraft.potion.StunMobEffect;
import org.imgaine.gaigegaigekaigecraft.potion.SukunaEffectMobEffect;
import org.imgaine.gaigegaigekaigecraft.potion.UnstableMobEffect;
import org.imgaine.gaigegaigekaigecraft.potion.ZoneMobEffect;
import net.minecraft.world.effect.MobEffect;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class JujutsucraftModMobEffects {
   public static final DeferredRegister<MobEffect> REGISTRY;
   public static final RegistryObject<MobEffect> CURSED_TECHNIQUE;
   public static final RegistryObject<MobEffect> INFINITY_EFFECT;
   public static final RegistryObject<MobEffect> DOMAIN_EXPANSION;
   public static final RegistryObject<MobEffect> NEUTRALIZATION;
   public static final RegistryObject<MobEffect> COOLDOWN_TIME;
   public static final RegistryObject<MobEffect> ZONE;
   public static final RegistryObject<MobEffect> SIMPLE_DOMAIN;
   public static final RegistryObject<MobEffect> PHYSICAL_GIFTED_EFFECT;
   public static final RegistryObject<MobEffect> CANCEL_CURSED_TECHNIQUE;
   public static final RegistryObject<MobEffect> SIX_EYES;
   public static final RegistryObject<MobEffect> GUARD;
   public static final RegistryObject<MobEffect> SPECIAL;
   public static final RegistryObject<MobEffect> PROJECTION_SORCERY;
   public static final RegistryObject<MobEffect> CONVERGENCE;
   public static final RegistryObject<MobEffect> STAR_RAGE;
   public static final RegistryObject<MobEffect> DEATH_PAINTING_BLOOD;
   public static final RegistryObject<MobEffect> REVERSE_CURSED_TECHNIQUE;
   public static final RegistryObject<MobEffect> DOMAIN_AMPLIFICATION;
   public static final RegistryObject<MobEffect> UNSTABLE;
   public static final RegistryObject<MobEffect> COOLDOWN_TIME_BACK_STEP;
   public static final RegistryObject<MobEffect> COOLDOWN_TIME_SIMPLE_DOMAIN;
   public static final RegistryObject<MobEffect> COMEDIAN;
   public static final RegistryObject<MobEffect> SCALE_CHANGE;
   public static final RegistryObject<MobEffect> SUKUNA_EFFECT;
   public static final RegistryObject<MobEffect> MYTHICAL_BEAST_AMBER_EFFECT;
   public static final RegistryObject<MobEffect> INSTANT_SPIRIT_BODYOF_DISTORTED_KILLING_EFFECT;
   public static final RegistryObject<MobEffect> FALLING_BLOSSOM_EMOTION;
   public static final RegistryObject<MobEffect> COOLDOWN_TIME_COMBAT;
   public static final RegistryObject<MobEffect> FLY_EFFECT;
   public static final RegistryObject<MobEffect> DOUBLE_JUMP_EFFECT;
   public static final RegistryObject<MobEffect> JACKPOT;
   public static final RegistryObject<MobEffect> PRAYER_SONG;
   public static final RegistryObject<MobEffect> INSECT_ARMOR_TECHNIQUE;
   public static final RegistryObject<MobEffect> CURSED_POISON;
   public static final RegistryObject<MobEffect> FATIGUE;
   public static final RegistryObject<MobEffect> BRAIN_DAMAGE;
   public static final RegistryObject<MobEffect> DAMAGE_EFFECT;
   public static final RegistryObject<MobEffect> EFFECT_KIRIN;
   public static final RegistryObject<MobEffect> EFFECT_REIKI;
   public static final RegistryObject<MobEffect> HIGH_SPEED;
   public static final RegistryObject<MobEffect> IGNORE_GUARD;
   public static final RegistryObject<MobEffect> DEEP_CONCENTRATION;
   public static final RegistryObject<MobEffect> COOLDOWN_TIME_GUARD;
   public static final RegistryObject<MobEffect> STUN;
   public static final RegistryObject<MobEffect> ATTACKING;

   public JujutsucraftModMobEffects() {
   }

   static {
      REGISTRY = DeferredRegister.create(ForgeRegistries.MOB_EFFECTS, "jujutsucraft");
      CURSED_TECHNIQUE = REGISTRY.register("cursed_technique", () -> new CursedTechniqueMobEffect());
      INFINITY_EFFECT = REGISTRY.register("infinity_effect", () -> new EffectInfinityMobEffect());
      DOMAIN_EXPANSION = REGISTRY.register("domain_expansion", () -> new DomainExpansionMobEffect());
      NEUTRALIZATION = REGISTRY.register("neutralization", () -> new NeutralizationMobEffect());
      COOLDOWN_TIME = REGISTRY.register("cooldown_time", () -> new CooldownTimeMobEffect());
      ZONE = REGISTRY.register("zone", () -> new ZoneMobEffect());
      SIMPLE_DOMAIN = REGISTRY.register("simple_domain", () -> new SimpleDomainMobEffect());
      PHYSICAL_GIFTED_EFFECT = REGISTRY.register("physical_gifted_effect", () -> new PhysicalGiftedEffectMobEffect());
      CANCEL_CURSED_TECHNIQUE = REGISTRY.register("cancel_cursed_technique", () -> new CancelCursedTechniqueMobEffect());
      SIX_EYES = REGISTRY.register("six_eyes", () -> new SixEyesMobEffect());
      GUARD = REGISTRY.register("guard", () -> new GuardMobEffect());
      SPECIAL = REGISTRY.register("special", () -> new SpecialMobEffect());
      PROJECTION_SORCERY = REGISTRY.register("projection_sorcery", () -> new ProjectionSorceryMobEffect());
      CONVERGENCE = REGISTRY.register("convergence", () -> new ConvergenceMobEffect());
      STAR_RAGE = REGISTRY.register("star_rage", () -> new StarRageMobEffect());
      DEATH_PAINTING_BLOOD = REGISTRY.register("death_painting_blood", () -> new DeathPaintingBloodMobEffect());
      REVERSE_CURSED_TECHNIQUE = REGISTRY.register("reverse_cursed_technique", () -> new ReverseCursedTechniqueMobEffect());
      DOMAIN_AMPLIFICATION = REGISTRY.register("domain_amplification", () -> new DomainAmplificationMobEffect());
      UNSTABLE = REGISTRY.register("unstable", () -> new UnstableMobEffect());
      COOLDOWN_TIME_BACK_STEP = REGISTRY.register("cooldown_time_back_step", () -> new CooldownTimeBackStepMobEffect());
      COOLDOWN_TIME_SIMPLE_DOMAIN = REGISTRY.register("cooldown_time_simple_domain", () -> new CooldownTimeSimpleDomainMobEffect());
      COMEDIAN = REGISTRY.register("comedian", () -> new ComedianMobEffect());
      SCALE_CHANGE = REGISTRY.register("scale_change", () -> new ScaleChangeMobEffect());
      SUKUNA_EFFECT = REGISTRY.register("sukuna_effect", () -> new SukunaEffectMobEffect());
      MYTHICAL_BEAST_AMBER_EFFECT = REGISTRY.register("mythical_beast_amber_effect", () -> new MythicalBeastAmberEffectMobEffect());
      INSTANT_SPIRIT_BODYOF_DISTORTED_KILLING_EFFECT = REGISTRY.register("instant_spirit_bodyof_distorted_killing_effect", () -> new InstantSpiritBodyofDistortedKillingEffectMobEffect());
      FALLING_BLOSSOM_EMOTION = REGISTRY.register("falling_blossom_emotion", () -> new FallingBlossomEmotionMobEffect());
      COOLDOWN_TIME_COMBAT = REGISTRY.register("cooldown_time_combat", () -> new CooldownTimeCombatMobEffect());
      FLY_EFFECT = REGISTRY.register("fly_effect", () -> new FlyEffectMobEffect());
      DOUBLE_JUMP_EFFECT = REGISTRY.register("double_jump_effect", () -> new DoubleJumpEffectMobEffect());
      JACKPOT = REGISTRY.register("jackpot", () -> new JackpotMobEffect());
      PRAYER_SONG = REGISTRY.register("prayer_song", () -> new PrayerSongMobEffect());
      INSECT_ARMOR_TECHNIQUE = REGISTRY.register("insect_armor_technique", () -> new InsectArmorTechniqueMobEffect());
      CURSED_POISON = REGISTRY.register("cursed_poison", () -> new CursedPoisonMobEffect());
      FATIGUE = REGISTRY.register("fatigue", () -> new FatigueMobEffect());
      BRAIN_DAMAGE = REGISTRY.register("brain_damage", () -> new BrainDamageMobEffect());
      DAMAGE_EFFECT = REGISTRY.register("damage_effect", () -> new DamageEffectMobEffect());
      EFFECT_KIRIN = REGISTRY.register("effect_kirin", () -> new EffectKirinMobEffect());
      EFFECT_REIKI = REGISTRY.register("effect_reiki", () -> new EffectReikiMobEffect());
      HIGH_SPEED = REGISTRY.register("high_speed", () -> new HighSpeedMobEffect());
      IGNORE_GUARD = REGISTRY.register("ignore_guard", () -> new IgnoreGuardMobEffect());
      DEEP_CONCENTRATION = REGISTRY.register("deep_concentration", () -> new DeepConcentrationMobEffect());
      COOLDOWN_TIME_GUARD = REGISTRY.register("cooldown_time_guard", () -> new CooldownTimeGuardMobEffect());
      STUN = REGISTRY.register("stun", () -> new StunMobEffect());
      ATTACKING = REGISTRY.register("attacking", () -> new AttackingMobEffect());
   }
}
