package org.imgaine.gaigegaigekaigecraft.init;

import org.imgaine.gaigegaigekaigecraft.item.ArmorInstantSpiritBodyofDistortedKillingItem;
import org.imgaine.gaigegaigekaigecraft.item.BlackRopeItem;
import org.imgaine.gaigegaigekaigecraft.item.BlazingCourageItem;
import org.imgaine.gaigegaigekaigecraft.item.BlindfoldBandageItem;
import org.imgaine.gaigegaigekaigecraft.item.BroomItem;
import org.imgaine.gaigegaigekaigecraft.item.BulletBallItem;
import org.imgaine.gaigegaigekaigecraft.item.BulletFlameItem;
import org.imgaine.gaigegaigekaigecraft.item.ClawsItem;
import org.imgaine.gaigegaigekaigecraft.item.ClothesAngelItem;
import org.imgaine.gaigegaigekaigecraft.item.ClothesChosoItem;
import org.imgaine.gaigegaigekaigecraft.item.ClothesDagonItem;
import org.imgaine.gaigegaigekaigecraft.item.ClothesDecisiveBattleItem;
import org.imgaine.gaigegaigekaigecraft.item.ClothesFushiguroTojiItem;
import org.imgaine.gaigegaigekaigecraft.item.ClothesGetoItem;
import org.imgaine.gaigegaigekaigecraft.item.ClothesHakariKinjiItem;
import org.imgaine.gaigegaigekaigecraft.item.ClothesInoTakuma1Item;
import org.imgaine.gaigegaigekaigecraft.item.ClothesInoTakuma2Item;
import org.imgaine.gaigegaigekaigecraft.item.ClothesIshigoriItem;
import org.imgaine.gaigegaigekaigecraft.item.ClothesJogoItem;
import org.imgaine.gaigegaigekaigecraft.item.ClothesKashimoHajimeItem;
import org.imgaine.gaigegaigekaigecraft.item.ClothesKiraraItem;
import org.imgaine.gaigegaigekaigecraft.item.ClothesKusakabeItem;
import org.imgaine.gaigegaigekaigecraft.item.ClothesMiguelItem;
import org.imgaine.gaigegaigekaigecraft.item.ClothesNanamiItem;
import org.imgaine.gaigegaigekaigecraft.item.ClothesNishimiyaItem;
import org.imgaine.gaigegaigekaigecraft.item.ClothesReggieStarItem;
import org.imgaine.gaigegaigekaigecraft.item.ClothesSukunaFushiguroItem;
import org.imgaine.gaigegaigekaigecraft.item.ClothesTodoAoiItem;
import org.imgaine.gaigegaigekaigecraft.item.ClothesUraumeItem;
import org.imgaine.gaigegaigekaigecraft.item.ClothesUroItem;
import org.imgaine.gaigegaigekaigecraft.item.ClothesYorozuItem;
import org.imgaine.gaigegaigekaigecraft.item.ClothesZenin2Item;
import org.imgaine.gaigegaigekaigecraft.item.ClothesZeninItem;
import org.imgaine.gaigegaigekaigecraft.item.ClothesZeninNaobitoItem;
import org.imgaine.gaigegaigekaigecraft.item.CopiedCursedTechniqueItem;
import org.imgaine.gaigegaigekaigecraft.item.CostumeTakabaItem;
import org.imgaine.gaigegaigekaigecraft.item.CursedSpiritArmouryItem;
import org.imgaine.gaigegaigekaigecraft.item.CursedSpiritBallItem;
import org.imgaine.gaigegaigekaigecraft.item.CursedTechniqueChangerItem;
import org.imgaine.gaigegaigekaigecraft.item.CursedTechniqueStarterItem;
import org.imgaine.gaigegaigekaigecraft.item.DeathPaintingItem;
import org.imgaine.gaigegaigekaigecraft.item.DebuggerJrItem;
import org.imgaine.gaigegaigekaigecraft.item.DragonBoneItem;
import org.imgaine.gaigegaigekaigecraft.item.ExecutionersSwordItem;
import org.imgaine.gaigegaigekaigecraft.item.FesterLifeBladeItem;
import org.imgaine.gaigegaigekaigecraft.item.GStaffItem;
import org.imgaine.gaigegaigekaigecraft.item.GarudaItemBallItem;
import org.imgaine.gaigegaigekaigecraft.item.GarudaItemItem;
import org.imgaine.gaigegaigekaigecraft.item.GavelBigItem;
import org.imgaine.gaigegaigekaigecraft.item.GavelItem;
import org.imgaine.gaigegaigekaigecraft.item.GavelLongItem;
import org.imgaine.gaigegaigekaigecraft.item.GlassesMakiItem;
import org.imgaine.gaigegaigekaigecraft.item.HairFushiguroMegumiItem;
import org.imgaine.gaigegaigekaigecraft.item.HammerItem;
import org.imgaine.gaigegaigekaigecraft.item.HanamiEyeItem;
import org.imgaine.gaigegaigekaigecraft.item.HanamiHandItem;
import org.imgaine.gaigegaigekaigecraft.item.HarisenItem;
import org.imgaine.gaigegaigekaigecraft.item.HeadJetItem;
import org.imgaine.gaigegaigekaigecraft.item.HeadPropellerItem;
import org.imgaine.gaigegaigekaigecraft.item.HitenItem;
import org.imgaine.gaigegaigekaigecraft.item.HumanStockCarItem;
import org.imgaine.gaigegaigekaigecraft.item.HumanStockItem;
import org.imgaine.gaigegaigekaigecraft.item.InsectArmorItem;
import org.imgaine.gaigegaigekaigecraft.item.InvertedSpearOfHeavenItem;
import org.imgaine.gaigegaigekaigecraft.item.ItadoriArmItem;
import org.imgaine.gaigegaigekaigecraft.item.ItadoriYujiPaperItem;
import org.imgaine.gaigegaigekaigecraft.item.ItemDollItem;
import org.imgaine.gaigegaigekaigecraft.item.ItemInsectItem;
import org.imgaine.gaigegaigekaigecraft.item.ItemMasterDomainAmplificationItem;
import org.imgaine.gaigegaigekaigecraft.item.ItemMasterDomainExpansionItem;
import org.imgaine.gaigegaigekaigecraft.item.ItemMasterFallingBlossomEmotionItem;
import org.imgaine.gaigegaigekaigecraft.item.ItemMasterPhysicalGiftedItem;
import org.imgaine.gaigegaigekaigecraft.item.ItemMasterReverseCursedTechniqueItem;
import org.imgaine.gaigegaigekaigecraft.item.ItemMasterSimpleDomainItem;
import org.imgaine.gaigegaigekaigecraft.item.ItemMasterSixEyesItem;
import org.imgaine.gaigegaigekaigecraft.item.KnifeItem;
import org.imgaine.gaigegaigekaigecraft.item.KurourushiBodyItem;
import org.imgaine.gaigegaigekaigecraft.item.LoudspeakerItem;
import org.imgaine.gaigegaigekaigecraft.item.MahitoHand1Item;
import org.imgaine.gaigegaigekaigecraft.item.MahitoHand2Item;
import org.imgaine.gaigegaigekaigecraft.item.MahoragaBodyItem;
import org.imgaine.gaigegaigekaigecraft.item.MahoragaWheelItem;
import org.imgaine.gaigegaigekaigecraft.item.MeiMeiAxeItem;
import org.imgaine.gaigegaigekaigecraft.item.MuscularBodyItem;
import org.imgaine.gaigegaigekaigecraft.item.MythicalBeastAmberItem;
import org.imgaine.gaigegaigekaigecraft.item.NaginataItem;
import org.imgaine.gaigegaigekaigecraft.item.NailItem;
import org.imgaine.gaigegaigekaigecraft.item.NaoyaCursedSpiritBodyItem;
import org.imgaine.gaigegaigekaigecraft.item.NyoiStaffItem;
import org.imgaine.gaigegaigekaigecraft.item.PendantTodoAoiItem;
import org.imgaine.gaigegaigekaigecraft.item.PistolItem;
import org.imgaine.gaigegaigekaigecraft.item.PlayfulCloudItem;
import org.imgaine.gaigegaigekaigecraft.item.Recommendation1Item;
import org.imgaine.gaigegaigekaigecraft.item.Recommendation2Item;
import org.imgaine.gaigegaigekaigecraft.item.RikaBodyItem;
import org.imgaine.gaigegaigekaigecraft.item.ScissorsItem;
import org.imgaine.gaigegaigekaigecraft.item.SickleItem;
import org.imgaine.gaigegaigekaigecraft.item.SlaughterDemonItem;
import org.imgaine.gaigegaigekaigecraft.item.SplitSoulKatanaItem;
import org.imgaine.gaigegaigekaigecraft.item.SukunaBodyItem;
import org.imgaine.gaigegaigekaigecraft.item.SukunaFingerItem;
import org.imgaine.gaigegaigekaigecraft.item.SunglassesItem;
import org.imgaine.gaigegaigekaigecraft.item.SupremeMartialSolutionItem;
import org.imgaine.gaigegaigekaigecraft.item.SwordBlackItem;
import org.imgaine.gaigegaigekaigecraft.item.SwordKusakabeItem;
import org.imgaine.gaigegaigekaigecraft.item.SwordMiwaKasumiItem;
import org.imgaine.gaigegaigekaigecraft.item.SwordOfExterminationItem;
import org.imgaine.gaigegaigekaigecraft.item.SwordOgiItem;
import org.imgaine.gaigegaigekaigecraft.item.SwordOkkotsuYutaItem;
import org.imgaine.gaigegaigekaigecraft.item.SwordOptionItem;
import org.imgaine.gaigegaigekaigecraft.item.SwordShigemoItem;
import org.imgaine.gaigegaigekaigecraft.item.UniformGetoItem;
import org.imgaine.gaigegaigekaigecraft.item.UniformGojoItem;
import org.imgaine.gaigegaigekaigecraft.item.UniformHigurumaItem;
import org.imgaine.gaigegaigekaigecraft.item.UniformItadoriItem;
import org.imgaine.gaigegaigekaigecraft.item.UniformNormalItem;
import org.imgaine.gaigegaigekaigecraft.item.UniformOkkotsuItem;
import org.imgaine.gaigegaigekaigecraft.item.UniformQItem;
import org.imgaine.gaigegaigekaigecraft.item.WeaponNanamiItem;
import org.imgaine.gaigegaigekaigecraft.item.WingKingItem;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ArmorItem.Type;
import net.minecraft.world.level.block.Block;
import net.minecraftforge.common.ForgeSpawnEggItem;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class JujutsucraftModItems {
   public static final DeferredRegister<Item> REGISTRY;
   public static final RegistryObject<Item> CURSED_TECHNIQUE_CHANGER;
   public static final RegistryObject<Item> JUJUTSU_BARRIER;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_31_SPAWN_EGG;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_32_SPAWN_EGG;
   public static final RegistryObject<Item> UNIFORM_NORMAL_HELMET;
   public static final RegistryObject<Item> UNIFORM_NORMAL_CHESTPLATE;
   public static final RegistryObject<Item> UNIFORM_NORMAL_LEGGINGS;
   public static final RegistryObject<Item> UNIFORM_NORMAL_BOOTS;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_33_SPAWN_EGG;
   public static final RegistryObject<Item> JOGO_HEAD_SPAWN_EGG;
   public static final RegistryObject<Item> SOCCER_PLAYER_SPAWN_EGG;
   public static final RegistryObject<Item> JOGO_ASH_SPAWN_EGG;
   public static final RegistryObject<Item> COFFINOFTHE_IRONMOUNTAIN_1;
   public static final RegistryObject<Item> COFFINOFTHE_IRONMOUNTAIN_2;
   public static final RegistryObject<Item> BLOCK_GRAVEL;
   public static final RegistryObject<Item> DEBUGGER_JR;
   public static final RegistryObject<Item> SLAUGHTER_DEMON;
   public static final RegistryObject<Item> INVERTED_SPEAR_OF_HEAVEN;
   public static final RegistryObject<Item> STEVENSON_SCREEN_SPAWN_EGG;
   public static final RegistryObject<Item> SWORD_OKKOTSU_YUTA;
   public static final RegistryObject<Item> LOUDSPEAKER;
   public static final RegistryObject<Item> SWORD_BLACK;
   public static final RegistryObject<Item> DIVINE_DOG_WHITE_SPAWN_EGG;
   public static final RegistryObject<Item> DIVINE_DOG_BLACK_SPAWN_EGG;
   public static final RegistryObject<Item> UNIFORM_OKKOTSU_CHESTPLATE;
   public static final RegistryObject<Item> HAIR_FUSHIGURO_MEGUMI_HELMET;
   public static final RegistryObject<Item> GREAT_SERPENT_SPAWN_EGG;
   public static final RegistryObject<Item> MAX_ELEPHANT_SPAWN_EGG;
   public static final RegistryObject<Item> MAHORAGA_DOG_SPAWN_EGG;
   public static final RegistryObject<Item> MAHORAGA_FROG_SPAWN_EGG;
   public static final RegistryObject<Item> SWORD_OF_EXTERMINATION;
   public static final RegistryObject<Item> RABBIT_ESCAPE_SPAWN_EGG;
   public static final RegistryObject<Item> MAHORAGA_WHEEL_HELMET;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_34_SPAWN_EGG;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_35_SPAWN_EGG;
   public static final RegistryObject<Item> CURSED_SPIRIT_ARMOURY_CHESTPLATE;
   public static final RegistryObject<Item> GLASSES_MAKI_HELMET;
   public static final RegistryObject<Item> GLASSES_MAKI_CHESTPLATE;
   public static final RegistryObject<Item> GLASSES_MAKI_LEGGINGS;
   public static final RegistryObject<Item> NAGINATA;
   public static final RegistryObject<Item> UNIFORM_GOJO_HELMET;
   public static final RegistryObject<Item> UNIFORM_GOJO_CHESTPLATE;
   public static final RegistryObject<Item> UNIFORM_GOJO_LEGGINGS;
   public static final RegistryObject<Item> UNIFORM_GOJO_BOOTS;
   public static final RegistryObject<Item> BLINDFOLD_BANDAGE_HELMET;
   public static final RegistryObject<Item> SUNGLASSES_HELMET;
   public static final RegistryObject<Item> BLOCK_UNIVERSE;
   public static final RegistryObject<Item> IN_BARRIER;
   public static final RegistryObject<Item> BLOCK_RED;
   public static final RegistryObject<Item> ITEM_MASTER_PHYSICAL_GIFTED;
   public static final RegistryObject<Item> ITEM_MASTER_SIX_EYES;
   public static final RegistryObject<Item> WEAPON_NANAMI;
   public static final RegistryObject<Item> NYOI_STAFF;
   public static final RegistryObject<Item> DOMAIN_GRASS;
   public static final RegistryObject<Item> DOMAIN_SAND;
   public static final RegistryObject<Item> DOMAIN_WATER;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_36_SPAWN_EGG;
   public static final RegistryObject<Item> CLOTHES_FUSHIGURO_TOJI_CHESTPLATE;
   public static final RegistryObject<Item> CLOTHES_FUSHIGURO_TOJI_LEGGINGS;
   public static final RegistryObject<Item> CLOTHES_ZENIN_CHESTPLATE;
   public static final RegistryObject<Item> CLOTHES_ZENIN_LEGGINGS;
   public static final RegistryObject<Item> CLOTHES_ZENIN_BOOTS;
   public static final RegistryObject<Item> CLOTHES_KASHIMO_HAJIME_HELMET;
   public static final RegistryObject<Item> CLOTHES_KASHIMO_HAJIME_CHESTPLATE;
   public static final RegistryObject<Item> CLOTHES_KASHIMO_HAJIME_LEGGINGS;
   public static final RegistryObject<Item> CLOTHES_KASHIMO_HAJIME_BOOTS;
   public static final RegistryObject<Item> MEI_MEI_AXE;
   public static final RegistryObject<Item> SPLIT_SOUL_KATANA;
   public static final RegistryObject<Item> KECHIZU_SPAWN_EGG;
   public static final RegistryObject<Item> BLAZING_COURAGE;
   public static final RegistryObject<Item> SWORD_OGI;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_37_SPAWN_EGG;
   public static final RegistryObject<Item> RECOMMENDATION_1;
   public static final RegistryObject<Item> WING_KING_CHESTPLATE;
   public static final RegistryObject<Item> CROW_SPAWN_EGG;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_311_SPAWN_EGG;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_38_SPAWN_EGG;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_39_SPAWN_EGG;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_310_SPAWN_EGG;
   public static final RegistryObject<Item> SWORD_MIWA_KASUMI;
   public static final RegistryObject<Item> MUSCULAR_BODY_CHESTPLATE;
   public static final RegistryObject<Item> CLOTHES_TODO_AOI_LEGGINGS;
   public static final RegistryObject<Item> PENDANT_TODO_AOI;
   public static final RegistryObject<Item> CLOTHES_ZENIN_2_CHESTPLATE;
   public static final RegistryObject<Item> CLOTHES_ZENIN_2_LEGGINGS;
   public static final RegistryObject<Item> CLOTHES_ISHIGORI_HELMET;
   public static final RegistryObject<Item> CLOTHES_ISHIGORI_CHESTPLATE;
   public static final RegistryObject<Item> CLOTHES_ISHIGORI_LEGGINGS;
   public static final RegistryObject<Item> TOAD_2_SPAWN_EGG;
   public static final RegistryObject<Item> ITEM_MASTER_DOMAIN_EXPANSION;
   public static final RegistryObject<Item> RECOMMENDATION_2;
   public static final RegistryObject<Item> ITEM_MASTER_SIMPLE_DOMAIN;
   public static final RegistryObject<Item> ITEM_MASTER_REVERSE_CURSED_TECHNIQUE;
   public static final RegistryObject<Item> MAHITO_HAND_2;
   public static final RegistryObject<Item> HANAMI_HAND;
   public static final RegistryObject<Item> ITEM_INSECT;
   public static final RegistryObject<Item> DOMAIN_BONE;
   public static final RegistryObject<Item> SUKUNA_BODY_CHESTPLATE;
   public static final RegistryObject<Item> SUPREME_MARTIAL_SOLUTION;
   public static final RegistryObject<Item> HITEN;
   public static final RegistryObject<Item> PIERCING_OX_SPAWN_EGG;
   public static final RegistryObject<Item> ROUND_DEER_SPAWN_EGG;
   public static final RegistryObject<Item> COSTUME_TAKABA_HELMET;
   public static final RegistryObject<Item> COSTUME_TAKABA_CHESTPLATE;
   public static final RegistryObject<Item> COSTUME_TAKABA_LEGGINGS;
   public static final RegistryObject<Item> COSTUME_TAKABA_BOOTS;
   public static final RegistryObject<Item> HARISEN;
   public static final RegistryObject<Item> UNIFORM_GETO_LEGGINGS;
   public static final RegistryObject<Item> CLOTHES_GETO_HELMET;
   public static final RegistryObject<Item> CLOTHES_GETO_CHESTPLATE;
   public static final RegistryObject<Item> CLOTHES_GETO_LEGGINGS;
   public static final RegistryObject<Item> CLOTHES_GETO_BOOTS;
   public static final RegistryObject<Item> CURSED_SPIRIT_BALL;
   public static final RegistryObject<Item> CLOTHES_DECISIVE_BATTLE_HELMET;
   public static final RegistryObject<Item> CLOTHES_DECISIVE_BATTLE_CHESTPLATE;
   public static final RegistryObject<Item> CLOTHES_DECISIVE_BATTLE_LEGGINGS;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_312_SPAWN_EGG;
   public static final RegistryObject<Item> KUROURUSHI_BODY_HELMET;
   public static final RegistryObject<Item> KUROURUSHI_BODY_CHESTPLATE;
   public static final RegistryObject<Item> KUROURUSHI_BODY_LEGGINGS;
   public static final RegistryObject<Item> FESTER_LIFE_BLADE;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_23_SPAWN_EGG;
   public static final RegistryObject<Item> NAOYA_CURSED_SPIRIT_BODY_CHESTPLATE;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_13_SPAWN_EGG;
   public static final RegistryObject<Item> SCHOOL_BELL;
   public static final RegistryObject<Item> MAHORAGA_BODY_HELMET;
   public static final RegistryObject<Item> MAHORAGA_BODY_CHESTPLATE;
   public static final RegistryObject<Item> MAHORAGA_BODY_LEGGINGS;
   public static final RegistryObject<Item> DOMAIN_FLOWER;
   public static final RegistryObject<Item> GARUDA_SPAWN_EGG;
   public static final RegistryObject<Item> GARUDA_ITEM;
   public static final RegistryObject<Item> GARUDA_BALL_SPAWN_EGG;
   public static final RegistryObject<Item> GARUDA_ITEM_BALL;
   public static final RegistryObject<Item> RIKA_BODY_HELMET;
   public static final RegistryObject<Item> RIKA_BODY_CHESTPLATE;
   public static final RegistryObject<Item> CURSED_TECHNIQUE_STARTER;
   public static final RegistryObject<Item> HUMAN_STOCK;
   public static final RegistryObject<Item> HUMAN_CAR_SPAWN_EGG;
   public static final RegistryObject<Item> HUMAN_STOCK_CAR;
   public static final RegistryObject<Item> SUKUNA_FINGER;
   public static final RegistryObject<Item> ARMOR_INSTANT_SPIRIT_BODYOF_DISTORTED_KILLING_HELMET;
   public static final RegistryObject<Item> ARMOR_INSTANT_SPIRIT_BODYOF_DISTORTED_KILLING_CHESTPLATE;
   public static final RegistryObject<Item> ARMOR_INSTANT_SPIRIT_BODYOF_DISTORTED_KILLING_LEGGINGS;
   public static final RegistryObject<Item> DOMAIN_BLUE_SKY;
   public static final RegistryObject<Item> BULLET_FLAME;
   public static final RegistryObject<Item> DOMAIN_CLOUD;
   public static final RegistryObject<Item> DOMAIN_STONE_BRICKS;
   public static final RegistryObject<Item> CURSED_BLOCK;
   public static final RegistryObject<Item> DRAGON_BONE;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_24_SPAWN_EGG;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_14_SPAWN_EGG;
   public static final RegistryObject<Item> COCKROACHES_SPAWN_EGG;
   public static final RegistryObject<Item> KILLER_1_SPAWN_EGG;
   public static final RegistryObject<Item> JOGO_SPAWN_EGG;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_15_SPAWN_EGG;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_22_SPAWN_EGG;
   public static final RegistryObject<Item> TAKADA_SPAWN_EGG;
   public static final RegistryObject<Item> CLOTHES_URAUME_HELMET;
   public static final RegistryObject<Item> CLOTHES_URAUME_CHESTPLATE;
   public static final RegistryObject<Item> CLOTHES_URAUME_LEGGINGS;
   public static final RegistryObject<Item> CLOTHES_URAUME_BOOTS;
   public static final RegistryObject<Item> GAVEL;
   public static final RegistryObject<Item> DOMAIN_ICE;
   public static final RegistryObject<Item> UNIFORM_ITADORI_CHESTPLATE;
   public static final RegistryObject<Item> UNIFORM_ITADORI_LEGGINGS;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_25_SPAWN_EGG;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_02_SPAWN_EGG;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_03_SPAWN_EGG;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_05_SPAWN_EGG;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_16_SPAWN_EGG;
   public static final RegistryObject<Item> BATHYNOMUS_GIGANTEUS_SPAWN_EGG;
   public static final RegistryObject<Item> ITEM_MASTER_FALLING_BLOSSOM_EMOTION;
   public static final RegistryObject<Item> MERGED_BEAST_AGITO_SPAWN_EGG;
   public static final RegistryObject<Item> SICKLE;
   public static final RegistryObject<Item> DOMAIN_BLOOD;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_313_SPAWN_EGG;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_314_SPAWN_EGG;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_315_SPAWN_EGG;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_316_SPAWN_EGG;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_317_SPAWN_EGG;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_318_SPAWN_EGG;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_26_SPAWN_EGG;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_27_SPAWN_EGG;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_28_SPAWN_EGG;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_29_SPAWN_EGG;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_21_SPAWN_EGG;
   public static final RegistryObject<Item> CLOTHES_NANAMI_HELMET;
   public static final RegistryObject<Item> CLOTHES_NANAMI_CHESTPLATE;
   public static final RegistryObject<Item> CLOTHES_NANAMI_LEGGINGS;
   public static final RegistryObject<Item> CLOTHES_SUKUNA_FUSHIGURO_CHESTPLATE;
   public static final RegistryObject<Item> CLOTHES_ZENIN_NAOBITO_CHESTPLATE;
   public static final RegistryObject<Item> CLOTHES_CHOSO_HELMET;
   public static final RegistryObject<Item> CLOTHES_CHOSO_CHESTPLATE;
   public static final RegistryObject<Item> CLOTHES_JOGO_HELMET;
   public static final RegistryObject<Item> CLOTHES_JOGO_CHESTPLATE;
   public static final RegistryObject<Item> CLAWS;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_18_SPAWN_EGG;
   public static final RegistryObject<Item> SCISSORS;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_06_SPAWN_EGG;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_07_SPAWN_EGG;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_08_SPAWN_EGG;
   public static final RegistryObject<Item> COPIED_CURSED_TECHNIQUE;
   public static final RegistryObject<Item> RIKA_2_SPAWN_EGG;
   public static final RegistryObject<Item> RIKA_SPAWN_EGG;
   public static final RegistryObject<Item> ITEM_MASTER_DOMAIN_AMPLIFICATION;
   public static final RegistryObject<Item> DOMAIN_PLANKS;
   public static final RegistryObject<Item> EXECUTIONERS_SWORD;
   public static final RegistryObject<Item> GAVEL_LONG;
   public static final RegistryObject<Item> GAVEL_BIG;
   public static final RegistryObject<Item> UNIFORM_HIGURUMA_CHESTPLATE;
   public static final RegistryObject<Item> UNIFORM_HIGURUMA_LEGGINGS;
   public static final RegistryObject<Item> TOAD_SPAWN_EGG;
   public static final RegistryObject<Item> TODO_AOI_SPAWN_EGG;
   public static final RegistryObject<Item> EIGHT_HANDLED_SWROD_DIVERGENT_SILA_DIVINE_GENERAL_MAHORAGA_SPAWN_EGG;
   public static final RegistryObject<Item> TRUCK_SPAWN_EGG;
   public static final RegistryObject<ClothesAngelItem> CLOTHES_ANGEL_HELMET;
   public static final RegistryObject<ClothesAngelItem> CLOTHES_ANGEL_CHESTPLATE;
   public static final RegistryObject<ClothesDagonItem> CLOTHES_DAGON_HELMET;
   public static final RegistryObject<ClothesDagonItem> CLOTHES_DAGON_CHESTPLATE;
   public static final RegistryObject<Item> KNIFE;
   public static final RegistryObject<Item> SWORD_SHIGEMO;
   public static final RegistryObject<Item> HAMMER;
   public static final RegistryObject<Item> DOMAIN_PODZOL;
   public static final RegistryObject<Item> COCKROACH_LARVA_SPAWN_EGG;
   public static final RegistryObject<ClothesKusakabeItem> CLOTHES_KUSAKABE_CHESTPLATE;
   public static final RegistryObject<ClothesKusakabeItem> CLOTHES_KUSAKABE_LEGGINGS;
   public static final RegistryObject<Item> URO_TAKAKO_SPAWN_EGG;
   public static final RegistryObject<ClothesUroItem> CLOTHES_URO_HELMET;
   public static final RegistryObject<ClothesUroItem> CLOTHES_URO_CHESTPLATE;
   public static final RegistryObject<Item> CLOTHES_KIRARA_HELMET;
   public static final RegistryObject<Item> CLOTHES_KIRARA_CHESTPLATE;
   public static final RegistryObject<Item> CLOTHES_HAKARI_KINJI_HELMET;
   public static final RegistryObject<Item> CLOTHES_HAKARI_KINJI_CHESTPLATE;
   public static final RegistryObject<Item> CLOTHES_HAKARI_KINJI_LEGGINGS;
   public static final RegistryObject<Item> CLOTHES_HAKARI_KINJI_BOOTS;
   public static final RegistryObject<Item> OGAMI_SPAWN_EGG;
   public static final RegistryObject<Item> DOMAIN_WHITE;
   public static final RegistryObject<Item> BULLET_BALL;
   public static final RegistryObject<Item> CLOTHES_NISHIMIYA_HELMET;
   public static final RegistryObject<Item> CLOTHES_MIGUEL_HELMET;
   public static final RegistryObject<Item> CLOTHES_MIGUEL_CHESTPLATE;
   public static final RegistryObject<Item> CLOTHES_MIGUEL_LEGGINGS;
   public static final RegistryObject<Item> CLOTHES_MIGUEL_BOOTS;
   public static final RegistryObject<Item> UNIFORM_Q_HELMET;
   public static final RegistryObject<Item> UNIFORM_Q_CHESTPLATE;
   public static final RegistryObject<Item> UNIFORM_Q_LEGGINGS;
   public static final RegistryObject<Item> SWORD_KUSAKABE;
   public static final RegistryObject<Item> MIGUEL_DANCER_SPAWN_EGG;
   public static final RegistryObject<Item> CLOTHES_YOROZU_CHESTPLATE;
   public static final RegistryObject<Item> ROZETSU_SPAWN_EGG;
   public static final RegistryObject<Item> ZENIN_CHOJURO_SPAWN_EGG;
   public static final RegistryObject<Item> G_STAFF;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_319_SPAWN_EGG;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_210_SPAWN_EGG;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_211_SPAWN_EGG;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_212_SPAWN_EGG;
   public static final RegistryObject<Item> MOON_DREGS_SPAWN_EGG;
   public static final RegistryObject<Item> SWORD_OPTION;
   public static final RegistryObject<Item> PANDA_NORMAL_SPAWN_EGG;
   public static final RegistryObject<Item> DOLL_1_SPAWN_EGG;
   public static final RegistryObject<Item> ITEM_DOLL;
   public static final RegistryObject<Item> ITADORI_ARM;
   public static final RegistryObject<Item> BROOM;
   public static final RegistryObject<Item> ENTITY_BROOM_SPAWN_EGG;
   public static final RegistryObject<Item> NAIL;
   public static final RegistryObject<Item> SHIKIGAMI_HETEROCEPHALUS_GLABER_SPAWN_EGG;
   public static final RegistryObject<Item> SHIKIGAMI_PTEROSAUR_SPAWN_EGG;
   public static final RegistryObject<Item> DHRUV_LAKDAWALLA_SPAWN_EGG;
   public static final RegistryObject<Item> DOMAIN;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_110_SPAWN_EGG;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_09_SPAWN_EGG;
   public static final RegistryObject<Item> CLOTHES_REGGIE_STAR_CHESTPLATE;
   public static final RegistryObject<InsectArmorItem> INSECT_ARMOR_HELMET;
   public static final RegistryObject<InsectArmorItem> INSECT_ARMOR_CHESTPLATE;
   public static final RegistryObject<InsectArmorItem> INSECT_ARMOR_LEGGINGS;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_213_SPAWN_EGG;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_214_SPAWN_EGG;
   public static final RegistryObject<Item> CLOTHES_INO_TAKUMA_1_HELMET;
   public static final RegistryObject<Item> CLOTHES_INO_TAKUMA_1_CHESTPLATE;
   public static final RegistryObject<Item> CLOTHES_INO_TAKUMA_1_LEGGINGS;
   public static final RegistryObject<Item> CLOTHES_INO_TAKUMA_1_BOOTS;
   public static final RegistryObject<Item> CLOTHES_INO_TAKUMA_2_HELMET;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_321_SPAWN_EGG;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_322_SPAWN_EGG;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_215_SPAWN_EGG;
   public static final RegistryObject<Item> PISTOL;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_111_SPAWN_EGG;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_216_SPAWN_EGG;
   public static final RegistryObject<Item> ROZETSU_SHIKIGAMI_VESSEL_SPAWN_EGG;
   public static final RegistryObject<Item> ROZETSU_SHIKIGAMI_VESSEL_2_SPAWN_EGG;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_04_SPAWN_EGG;
   public static final RegistryObject<HeadJetItem> HEAD_JET_HELMET;
   public static final RegistryObject<HeadPropellerItem> HEAD_PROPELLER_HELMET;
   public static final RegistryObject<Item> ITADORI_YUJI_SPAWN_EGG;
   public static final RegistryObject<Item> ITADORI_YUJI_SHIBUYA_SPAWN_EGG;
   public static final RegistryObject<Item> ITADORI_YUJI_SHINJUKU_SPAWN_EGG;
   public static final RegistryObject<Item> FUSHIGURO_MEGUMI_SPAWN_EGG;
   public static final RegistryObject<Item> FUSHIGURO_MEGUMI_SHIBUYA_SPAWN_EGG;
   public static final RegistryObject<Item> NOBARA_KUGISAKI_SPAWN_EGG;
   public static final RegistryObject<Item> INUMAKI_TOGE_SPAWN_EGG;
   public static final RegistryObject<Item> ZENIN_MAKI_SPAWN_EGG;
   public static final RegistryObject<Item> ZENIN_MAKI_CULLING_GAME_SPAWN_EGG;
   public static final RegistryObject<Item> OKKOTSU_YUTA_SPAWN_EGG;
   public static final RegistryObject<Item> OKKOTSU_YUTA_CULLING_GAME_SPAWN_EGG;
   public static final RegistryObject<Item> HOSHI_KIRARA_SPAWN_EGG;
   public static final RegistryObject<Item> HAKARI_KINJI_SPAWN_EGG;
   public static final RegistryObject<Item> YAGA_MASAMICHI_SPAWN_EGG;
   public static final RegistryObject<Item> KUSAKABE_ATSUYA_SPAWN_EGG;
   public static final RegistryObject<Item> MIWA_KASUMI_SPAWN_EGG;
   public static final RegistryObject<Item> NISHIMIYA_MOMO_SPAWN_EGG;
   public static final RegistryObject<Item> KAMO_NORITOSHI_SPAWN_EGG;
   public static final RegistryObject<Item> MECHAMARU_SPAWN_EGG;
   public static final RegistryObject<Item> GETO_SUGURU_SPAWN_EGG;
   public static final RegistryObject<Item> GETO_SUGURU_CURSE_USER_SPAWN_EGG;
   public static final RegistryObject<Item> KENJAKU_SPAWN_EGG;
   public static final RegistryObject<Item> GOJO_SATORU_SCHOOL_DAYS_SPAWN_EGG;
   public static final RegistryObject<Item> GOJO_SATORU_SPAWN_EGG;
   public static final RegistryObject<Item> JUJUTSU_SORCERER_SPAWN_EGG;
   public static final RegistryObject<Item> MEI_MEI_SPAWN_EGG;
   public static final RegistryObject<Item> NANAMI_KENTO_SPAWN_EGG;
   public static final RegistryObject<Item> TSUKUMO_YUKI_SPAWN_EGG;
   public static final RegistryObject<Item> INO_TAKUMA_SPAWN_EGG;
   public static final RegistryObject<Item> ZENIN_NAOBITO_SPAWN_EGG;
   public static final RegistryObject<Item> ZENIN_NAOYA_SPAWN_EGG;
   public static final RegistryObject<Item> ZENIN_JINICHI_SPAWN_EGG;
   public static final RegistryObject<Item> ZENIN_OGI_SPAWN_EGG;
   public static final RegistryObject<Item> YOSHINO_JUNPEI_SPAWN_EGG;
   public static final RegistryObject<Item> ZENIN_RANTA_SPAWN_EGG;
   public static final RegistryObject<Item> KUKURU_SPAWN_EGG;
   public static final RegistryObject<Item> FUSHIGURO_TOJI_SPAWN_EGG;
   public static final RegistryObject<Item> FUSHIGURO_TOJI_BUG_SPAWN_EGG;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_01_SPAWN_EGG;
   public static final RegistryObject<Item> CURSE_USER_SPAWN_EGG;
   public static final RegistryObject<Item> CURSE_USER_1_SPAWN_EGG;
   public static final RegistryObject<Item> Q_SPAWN_EGG;
   public static final RegistryObject<Item> MIMIKO_SPAWN_EGG;
   public static final RegistryObject<Item> NANAKO_SPAWN_EGG;
   public static final RegistryObject<Item> NEGI_TOSHIHISA_SPAWN_EGG;
   public static final RegistryObject<Item> LARUE_SPAWN_EGG;
   public static final RegistryObject<Item> MIGUEL_SPAWN_EGG;
   public static final RegistryObject<Item> KUMIYA_JUZO_SPAWN_EGG;
   public static final RegistryObject<Item> AWASAKA_JIRO_SPAWN_EGG;
   public static final RegistryObject<Item> HANAMI_SPAWN_EGG;
   public static final RegistryObject<Item> MAHITO_SPAWN_EGG;
   public static final RegistryObject<Item> URAUME_SPAWN_EGG;
   public static final RegistryObject<Item> SUKUNA_SPAWN_EGG;
   public static final RegistryObject<Item> SUKUNA_FUSHIGURO_SPAWN_EGG;
   public static final RegistryObject<Item> SUKUNA_PERFECT_SPAWN_EGG;
   public static final RegistryObject<Item> ESO_SPAWN_EGG;
   public static final RegistryObject<Item> CHOSO_SPAWN_EGG;
   public static final RegistryObject<Item> HABA_SPAWN_EGG;
   public static final RegistryObject<Item> HANYU_SPAWN_EGG;
   public static final RegistryObject<Item> TAKABA_FUMIHIKO_SPAWN_EGG;
   public static final RegistryObject<Item> HIGURUMA_HIROMI_SPAWN_EGG;
   public static final RegistryObject<Item> CHARLES_BERNARD_SPAWN_EGG;
   public static final RegistryObject<Item> ISHIGORI_RYU_SPAWN_EGG;
   public static final RegistryObject<Item> KASHIMO_HAJIME_SPAWN_EGG;
   public static final RegistryObject<Item> KURUSU_HANA_SPAWN_EGG;
   public static final RegistryObject<Item> HAZENOKI_SPAWN_EGG;
   public static final RegistryObject<Item> REGGIE_STAR_SPAWN_EGG;
   public static final RegistryObject<Item> DAIDO_HAGANE_SPAWN_EGG;
   public static final RegistryObject<Item> MIYO_ROKUJUSHI_SPAWN_EGG;
   public static final RegistryObject<Item> YOROZU_SPAWN_EGG;
   public static final RegistryObject<Item> ROZETSU_SHIKIGAMI_SPAWN_EGG;
   public static final RegistryObject<Item> TRANSFIGURED_HUMAN_SPAWN_EGG;
   public static final RegistryObject<Item> POLYMORPHIC_SOUL_ISOMER_SPAWN_EGG;
   public static final RegistryObject<HanamiEyeItem> HANAMI_EYE_HELMET;
   public static final RegistryObject<MythicalBeastAmberItem> MYTHICAL_BEAST_AMBER_HELMET;
   public static final RegistryObject<ItadoriYujiPaperItem> ITADORI_YUJI_PAPER_HELMET;
   public static final RegistryObject<Item> ZENIN_NAOYA_CURSED_SPIRIT_SPAWN_EGG;
   public static final RegistryObject<Item> DAGON_SPAWN_EGG;
   public static final RegistryObject<Item> SHIGEMO_HARUTA_SPAWN_EGG;
   public static final RegistryObject<Item> ORCASAN_SPAWN_EGG;
   public static final RegistryObject<Item> PLAYFUL_CLOUD;
   public static final RegistryObject<Item> BLACK_ROPE;
   public static final RegistryObject<Item> MAHITO_HAND_1;
   public static final RegistryObject<Item> DEATH_PAINTING;
   public static final RegistryObject<Item> DOMAIN_DARK_STONE;
   public static final RegistryObject<Item> DIVINE_DOG_TOTALITY_SPAWN_EGG;
   public static final RegistryObject<Item> NUE_SPAWN_EGG;
   public static final RegistryObject<Item> TIGER_FUNERAL_SPAWN_EGG;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_010_SPAWN_EGG;
   public static final RegistryObject<Item> CAR_SPAWN_EGG;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_323_SPAWN_EGG;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_19_SPAWN_EGG;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_12_SPAWN_EGG;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_011_SPAWN_EGG;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_012_SPAWN_EGG;
   public static final RegistryObject<Item> CURSED_SPIRIT_GRADE_11_SPAWN_EGG;

   public JujutsucraftModItems() {
   }

   private static RegistryObject<Item> block(RegistryObject<Block> block) {
      return REGISTRY.register(block.getId().m_135815_(), () -> new BlockItem((Block)block.get(), new Item.Properties()));
   }

   static {
      REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, "jujutsucraft");
      CURSED_TECHNIQUE_CHANGER = REGISTRY.register("cursed_technique_changer", () -> new CursedTechniqueChangerItem());
      JUJUTSU_BARRIER = block(JujutsucraftModBlocks.JUJUTSU_BARRIER);
      CURSED_SPIRIT_GRADE_31_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_31_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_31, -1, -1, new Item.Properties()));
      CURSED_SPIRIT_GRADE_32_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_32_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_32, -1, -1, new Item.Properties()));
      UNIFORM_NORMAL_HELMET = REGISTRY.register("uniform_normal_helmet", () -> new UniformNormalItem.Helmet());
      UNIFORM_NORMAL_CHESTPLATE = REGISTRY.register("uniform_normal_chestplate", () -> new UniformNormalItem.Chestplate());
      UNIFORM_NORMAL_LEGGINGS = REGISTRY.register("uniform_normal_leggings", () -> new UniformNormalItem.Leggings());
      UNIFORM_NORMAL_BOOTS = REGISTRY.register("uniform_normal_boots", () -> new UniformNormalItem.Boots());
      CURSED_SPIRIT_GRADE_33_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_33_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_33, -1, -1, new Item.Properties()));
      JOGO_HEAD_SPAWN_EGG = REGISTRY.register("jogo_head_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.JOGO_HEAD, -16737997, -16777216, new Item.Properties()));
      SOCCER_PLAYER_SPAWN_EGG = REGISTRY.register("soccer_player_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.SOCCER_PLAYER, -16776961, -65536, new Item.Properties()));
      JOGO_ASH_SPAWN_EGG = REGISTRY.register("jogo_ash_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.JOGO_ASH, -16737997, -16777216, new Item.Properties()));
      COFFINOFTHE_IRONMOUNTAIN_1 = block(JujutsucraftModBlocks.COFFINOFTHE_IRONMOUNTAIN_1);
      COFFINOFTHE_IRONMOUNTAIN_2 = block(JujutsucraftModBlocks.COFFINOFTHE_IRONMOUNTAIN_2);
      BLOCK_GRAVEL = block(JujutsucraftModBlocks.BLOCK_GRAVEL);
      DEBUGGER_JR = REGISTRY.register("debugger_jr", () -> new DebuggerJrItem());
      SLAUGHTER_DEMON = REGISTRY.register("slaughter_demon", () -> new SlaughterDemonItem());
      INVERTED_SPEAR_OF_HEAVEN = REGISTRY.register("inverted_spear_of_heaven", () -> new InvertedSpearOfHeavenItem());
      STEVENSON_SCREEN_SPAWN_EGG = REGISTRY.register("stevenson_screen_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.STEVENSON_SCREEN, -1, -1, new Item.Properties()));
      SWORD_OKKOTSU_YUTA = REGISTRY.register("sword_okkotsu_yuta", () -> new SwordOkkotsuYutaItem());
      LOUDSPEAKER = REGISTRY.register("loudspeaker", () -> new LoudspeakerItem());
      SWORD_BLACK = REGISTRY.register("sword_black", () -> new SwordBlackItem());
      DIVINE_DOG_WHITE_SPAWN_EGG = REGISTRY.register("divine_dog_white_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.DIVINE_DOG_WHITE, -16777216, -16777216, new Item.Properties()));
      DIVINE_DOG_BLACK_SPAWN_EGG = REGISTRY.register("divine_dog_black_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.DIVINE_DOG_BLACK, -16777216, -16777216, new Item.Properties()));
      UNIFORM_OKKOTSU_CHESTPLATE = REGISTRY.register("uniform_okkotsu_chestplate", () -> new UniformOkkotsuItem.Chestplate());
      HAIR_FUSHIGURO_MEGUMI_HELMET = REGISTRY.register("hair_fushiguro_megumi_helmet", () -> new HairFushiguroMegumiItem.Helmet());
      GREAT_SERPENT_SPAWN_EGG = REGISTRY.register("great_serpent_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.GREAT_SERPENT, -16777216, -16777216, new Item.Properties()));
      MAX_ELEPHANT_SPAWN_EGG = REGISTRY.register("max_elephant_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.MAX_ELEPHANT, -16777216, -16777216, new Item.Properties()));
      MAHORAGA_DOG_SPAWN_EGG = REGISTRY.register("mahoraga_dog_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.MAHORAGA_DOG, -16777216, -16777216, new Item.Properties()));
      MAHORAGA_FROG_SPAWN_EGG = REGISTRY.register("mahoraga_frog_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.MAHORAGA_FROG, -16777216, -16777216, new Item.Properties()));
      SWORD_OF_EXTERMINATION = REGISTRY.register("sword_of_extermination", () -> new SwordOfExterminationItem());
      RABBIT_ESCAPE_SPAWN_EGG = REGISTRY.register("rabbit_escape_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.RABBIT_ESCAPE, -16777216, -16777216, new Item.Properties()));
      MAHORAGA_WHEEL_HELMET = REGISTRY.register("mahoraga_wheel_helmet", () -> new MahoragaWheelItem.Helmet());
      CURSED_SPIRIT_GRADE_34_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_34_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_34, -1, -1, new Item.Properties()));
      CURSED_SPIRIT_GRADE_35_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_35_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_35, -1, -1, new Item.Properties()));
      CURSED_SPIRIT_ARMOURY_CHESTPLATE = REGISTRY.register("cursed_spirit_armoury_chestplate", () -> new CursedSpiritArmouryItem.Chestplate());
      GLASSES_MAKI_HELMET = REGISTRY.register("glasses_maki_helmet", () -> new GlassesMakiItem.Helmet());
      GLASSES_MAKI_CHESTPLATE = REGISTRY.register("glasses_maki_chestplate", () -> new GlassesMakiItem.Chestplate());
      GLASSES_MAKI_LEGGINGS = REGISTRY.register("glasses_maki_leggings", () -> new GlassesMakiItem.Leggings());
      NAGINATA = REGISTRY.register("naginata", () -> new NaginataItem());
      UNIFORM_GOJO_HELMET = REGISTRY.register("uniform_gojo_helmet", () -> new UniformGojoItem.Helmet());
      UNIFORM_GOJO_CHESTPLATE = REGISTRY.register("uniform_gojo_chestplate", () -> new UniformGojoItem.Chestplate());
      UNIFORM_GOJO_LEGGINGS = REGISTRY.register("uniform_gojo_leggings", () -> new UniformGojoItem.Leggings());
      UNIFORM_GOJO_BOOTS = REGISTRY.register("uniform_gojo_boots", () -> new UniformGojoItem.Boots());
      BLINDFOLD_BANDAGE_HELMET = REGISTRY.register("blindfold_bandage_helmet", () -> new BlindfoldBandageItem.Helmet());
      SUNGLASSES_HELMET = REGISTRY.register("sunglasses_helmet", () -> new SunglassesItem.Helmet());
      BLOCK_UNIVERSE = block(JujutsucraftModBlocks.BLOCK_UNIVERSE);
      IN_BARRIER = block(JujutsucraftModBlocks.IN_BARRIER);
      BLOCK_RED = block(JujutsucraftModBlocks.BLOCK_RED);
      ITEM_MASTER_PHYSICAL_GIFTED = REGISTRY.register("item_master_physical_gifted", () -> new ItemMasterPhysicalGiftedItem());
      ITEM_MASTER_SIX_EYES = REGISTRY.register("item_master_six_eyes", () -> new ItemMasterSixEyesItem());
      WEAPON_NANAMI = REGISTRY.register("weapon_nanami", () -> new WeaponNanamiItem());
      NYOI_STAFF = REGISTRY.register("nyoi_staff", () -> new NyoiStaffItem());
      DOMAIN_GRASS = block(JujutsucraftModBlocks.DOMAIN_GRASS);
      DOMAIN_SAND = block(JujutsucraftModBlocks.DOMAIN_SAND);
      DOMAIN_WATER = block(JujutsucraftModBlocks.DOMAIN_WATER);
      CURSED_SPIRIT_GRADE_36_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_36_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_36, -1, -1, new Item.Properties()));
      CLOTHES_FUSHIGURO_TOJI_CHESTPLATE = REGISTRY.register("clothes_fushiguro_toji_chestplate", () -> new ClothesFushiguroTojiItem.Chestplate());
      CLOTHES_FUSHIGURO_TOJI_LEGGINGS = REGISTRY.register("clothes_fushiguro_toji_leggings", () -> new ClothesFushiguroTojiItem.Leggings());
      CLOTHES_ZENIN_CHESTPLATE = REGISTRY.register("clothes_zenin_chestplate", () -> new ClothesZeninItem.Chestplate());
      CLOTHES_ZENIN_LEGGINGS = REGISTRY.register("clothes_zenin_leggings", () -> new ClothesZeninItem.Leggings());
      CLOTHES_ZENIN_BOOTS = REGISTRY.register("clothes_zenin_boots", () -> new ClothesZeninItem.Boots());
      CLOTHES_KASHIMO_HAJIME_HELMET = REGISTRY.register("clothes_kashimo_hajime_helmet", () -> new ClothesKashimoHajimeItem.Helmet());
      CLOTHES_KASHIMO_HAJIME_CHESTPLATE = REGISTRY.register("clothes_kashimo_hajime_chestplate", () -> new ClothesKashimoHajimeItem.Chestplate());
      CLOTHES_KASHIMO_HAJIME_LEGGINGS = REGISTRY.register("clothes_kashimo_hajime_leggings", () -> new ClothesKashimoHajimeItem.Leggings());
      CLOTHES_KASHIMO_HAJIME_BOOTS = REGISTRY.register("clothes_kashimo_hajime_boots", () -> new ClothesKashimoHajimeItem.Boots());
      MEI_MEI_AXE = REGISTRY.register("mei_mei_axe", () -> new MeiMeiAxeItem());
      SPLIT_SOUL_KATANA = REGISTRY.register("split_soul_katana", () -> new SplitSoulKatanaItem());
      KECHIZU_SPAWN_EGG = REGISTRY.register("kechizu_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.KECHIZU, -10092544, -16777114, new Item.Properties()));
      BLAZING_COURAGE = REGISTRY.register("blazing_courage", () -> new BlazingCourageItem());
      SWORD_OGI = REGISTRY.register("sword_ogi", () -> new SwordOgiItem());
      CURSED_SPIRIT_GRADE_37_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_37_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_37, -1, -1, new Item.Properties()));
      RECOMMENDATION_1 = REGISTRY.register("recommendation_1", () -> new Recommendation1Item());
      WING_KING_CHESTPLATE = REGISTRY.register("wing_king_chestplate", () -> new WingKingItem.Chestplate());
      CROW_SPAWN_EGG = REGISTRY.register("crow_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CROW, -1, -1, new Item.Properties()));
      CURSED_SPIRIT_GRADE_311_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_311_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_311, -1, -1, new Item.Properties()));
      CURSED_SPIRIT_GRADE_38_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_38_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_38, -1, -1, new Item.Properties()));
      CURSED_SPIRIT_GRADE_39_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_39_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_39, -1, -1, new Item.Properties()));
      CURSED_SPIRIT_GRADE_310_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_310_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_310, -1, -1, new Item.Properties()));
      SWORD_MIWA_KASUMI = REGISTRY.register("sword_miwa_kasumi", () -> new SwordMiwaKasumiItem());
      MUSCULAR_BODY_CHESTPLATE = REGISTRY.register("muscular_body_chestplate", () -> new MuscularBodyItem.Chestplate());
      CLOTHES_TODO_AOI_LEGGINGS = REGISTRY.register("clothes_todo_aoi_leggings", () -> new ClothesTodoAoiItem.Leggings());
      PENDANT_TODO_AOI = REGISTRY.register("pendant_todo_aoi", () -> new PendantTodoAoiItem());
      CLOTHES_ZENIN_2_CHESTPLATE = REGISTRY.register("clothes_zenin_2_chestplate", () -> new ClothesZenin2Item.Chestplate());
      CLOTHES_ZENIN_2_LEGGINGS = REGISTRY.register("clothes_zenin_2_leggings", () -> new ClothesZenin2Item.Leggings());
      CLOTHES_ISHIGORI_HELMET = REGISTRY.register("clothes_ishigori_helmet", () -> new ClothesIshigoriItem.Helmet());
      CLOTHES_ISHIGORI_CHESTPLATE = REGISTRY.register("clothes_ishigori_chestplate", () -> new ClothesIshigoriItem.Chestplate());
      CLOTHES_ISHIGORI_LEGGINGS = REGISTRY.register("clothes_ishigori_leggings", () -> new ClothesIshigoriItem.Leggings());
      TOAD_2_SPAWN_EGG = REGISTRY.register("toad_2_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.TOAD_2, -16777216, -16777216, new Item.Properties()));
      ITEM_MASTER_DOMAIN_EXPANSION = REGISTRY.register("item_master_domain_expansion", () -> new ItemMasterDomainExpansionItem());
      RECOMMENDATION_2 = REGISTRY.register("recommendation_2", () -> new Recommendation2Item());
      ITEM_MASTER_SIMPLE_DOMAIN = REGISTRY.register("item_master_simple_domain", () -> new ItemMasterSimpleDomainItem());
      ITEM_MASTER_REVERSE_CURSED_TECHNIQUE = REGISTRY.register("item_master_reverse_cursed_technique", () -> new ItemMasterReverseCursedTechniqueItem());
      MAHITO_HAND_2 = REGISTRY.register("mahito_hand_2", () -> new MahitoHand2Item());
      HANAMI_HAND = REGISTRY.register("hanami_hand", () -> new HanamiHandItem());
      ITEM_INSECT = REGISTRY.register("item_insect", () -> new ItemInsectItem());
      DOMAIN_BONE = block(JujutsucraftModBlocks.DOMAIN_BONE);
      SUKUNA_BODY_CHESTPLATE = REGISTRY.register("sukuna_body_chestplate", () -> new SukunaBodyItem.Chestplate());
      SUPREME_MARTIAL_SOLUTION = REGISTRY.register("supreme_martial_solution", () -> new SupremeMartialSolutionItem());
      HITEN = REGISTRY.register("hiten", () -> new HitenItem());
      PIERCING_OX_SPAWN_EGG = REGISTRY.register("piercing_ox_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.PIERCING_OX, -16777216, -16777216, new Item.Properties()));
      ROUND_DEER_SPAWN_EGG = REGISTRY.register("round_deer_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.ROUND_DEER, -16777216, -16777216, new Item.Properties()));
      COSTUME_TAKABA_HELMET = REGISTRY.register("costume_takaba_helmet", () -> new CostumeTakabaItem.Helmet());
      COSTUME_TAKABA_CHESTPLATE = REGISTRY.register("costume_takaba_chestplate", () -> new CostumeTakabaItem.Chestplate());
      COSTUME_TAKABA_LEGGINGS = REGISTRY.register("costume_takaba_leggings", () -> new CostumeTakabaItem.Leggings());
      COSTUME_TAKABA_BOOTS = REGISTRY.register("costume_takaba_boots", () -> new CostumeTakabaItem.Boots());
      HARISEN = REGISTRY.register("harisen", () -> new HarisenItem());
      UNIFORM_GETO_LEGGINGS = REGISTRY.register("uniform_geto_leggings", () -> new UniformGetoItem.Leggings());
      CLOTHES_GETO_HELMET = REGISTRY.register("clothes_geto_helmet", () -> new ClothesGetoItem.Helmet());
      CLOTHES_GETO_CHESTPLATE = REGISTRY.register("clothes_geto_chestplate", () -> new ClothesGetoItem.Chestplate());
      CLOTHES_GETO_LEGGINGS = REGISTRY.register("clothes_geto_leggings", () -> new ClothesGetoItem.Leggings());
      CLOTHES_GETO_BOOTS = REGISTRY.register("clothes_geto_boots", () -> new ClothesGetoItem.Boots());
      CURSED_SPIRIT_BALL = REGISTRY.register("cursed_spirit_ball", () -> new CursedSpiritBallItem());
      CLOTHES_DECISIVE_BATTLE_HELMET = REGISTRY.register("clothes_decisive_battle_helmet", () -> new ClothesDecisiveBattleItem.Helmet());
      CLOTHES_DECISIVE_BATTLE_CHESTPLATE = REGISTRY.register("clothes_decisive_battle_chestplate", () -> new ClothesDecisiveBattleItem.Chestplate());
      CLOTHES_DECISIVE_BATTLE_LEGGINGS = REGISTRY.register("clothes_decisive_battle_leggings", () -> new ClothesDecisiveBattleItem.Leggings());
      CURSED_SPIRIT_GRADE_312_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_312_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_312, -1, -1, new Item.Properties()));
      KUROURUSHI_BODY_HELMET = REGISTRY.register("kurourushi_body_helmet", () -> new KurourushiBodyItem.Helmet());
      KUROURUSHI_BODY_CHESTPLATE = REGISTRY.register("kurourushi_body_chestplate", () -> new KurourushiBodyItem.Chestplate());
      KUROURUSHI_BODY_LEGGINGS = REGISTRY.register("kurourushi_body_leggings", () -> new KurourushiBodyItem.Leggings());
      FESTER_LIFE_BLADE = REGISTRY.register("fester_life_blade", () -> new FesterLifeBladeItem());
      CURSED_SPIRIT_GRADE_23_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_23_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_23, -3355444, -3355444, new Item.Properties()));
      NAOYA_CURSED_SPIRIT_BODY_CHESTPLATE = REGISTRY.register("naoya_cursed_spirit_body_chestplate", () -> new NaoyaCursedSpiritBodyItem.Chestplate());
      CURSED_SPIRIT_GRADE_13_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_13_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_13, -6710887, -6710887, new Item.Properties()));
      SCHOOL_BELL = block(JujutsucraftModBlocks.SCHOOL_BELL);
      MAHORAGA_BODY_HELMET = REGISTRY.register("mahoraga_body_helmet", () -> new MahoragaBodyItem.Helmet());
      MAHORAGA_BODY_CHESTPLATE = REGISTRY.register("mahoraga_body_chestplate", () -> new MahoragaBodyItem.Chestplate());
      MAHORAGA_BODY_LEGGINGS = REGISTRY.register("mahoraga_body_leggings", () -> new MahoragaBodyItem.Leggings());
      DOMAIN_FLOWER = block(JujutsucraftModBlocks.DOMAIN_FLOWER);
      GARUDA_SPAWN_EGG = REGISTRY.register("garuda_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.GARUDA, -10066330, -3355444, new Item.Properties()));
      GARUDA_ITEM = REGISTRY.register("garuda_item", () -> new GarudaItemItem());
      GARUDA_BALL_SPAWN_EGG = REGISTRY.register("garuda_ball_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.GARUDA_BALL, -10066330, -3355444, new Item.Properties()));
      GARUDA_ITEM_BALL = REGISTRY.register("garuda_item_ball", () -> new GarudaItemBallItem());
      RIKA_BODY_HELMET = REGISTRY.register("rika_body_helmet", () -> new RikaBodyItem.Helmet());
      RIKA_BODY_CHESTPLATE = REGISTRY.register("rika_body_chestplate", () -> new RikaBodyItem.Chestplate());
      CURSED_TECHNIQUE_STARTER = REGISTRY.register("cursed_technique_starter", () -> new CursedTechniqueStarterItem());
      HUMAN_STOCK = REGISTRY.register("human_stock", () -> new HumanStockItem());
      HUMAN_CAR_SPAWN_EGG = REGISTRY.register("human_car_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.HUMAN_CAR, -1, -1, new Item.Properties()));
      HUMAN_STOCK_CAR = REGISTRY.register("human_stock_car", () -> new HumanStockCarItem());
      SUKUNA_FINGER = REGISTRY.register("sukuna_finger", () -> new SukunaFingerItem());
      ARMOR_INSTANT_SPIRIT_BODYOF_DISTORTED_KILLING_HELMET = REGISTRY.register("armor_instant_spirit_bodyof_distorted_killing_helmet", () -> new ArmorInstantSpiritBodyofDistortedKillingItem.Helmet());
      ARMOR_INSTANT_SPIRIT_BODYOF_DISTORTED_KILLING_CHESTPLATE = REGISTRY.register("armor_instant_spirit_bodyof_distorted_killing_chestplate", () -> new ArmorInstantSpiritBodyofDistortedKillingItem.Chestplate());
      ARMOR_INSTANT_SPIRIT_BODYOF_DISTORTED_KILLING_LEGGINGS = REGISTRY.register("armor_instant_spirit_bodyof_distorted_killing_leggings", () -> new ArmorInstantSpiritBodyofDistortedKillingItem.Leggings());
      DOMAIN_BLUE_SKY = block(JujutsucraftModBlocks.DOMAIN_BLUE_SKY);
      BULLET_FLAME = REGISTRY.register("bullet_flame", () -> new BulletFlameItem());
      DOMAIN_CLOUD = block(JujutsucraftModBlocks.DOMAIN_CLOUD);
      DOMAIN_STONE_BRICKS = block(JujutsucraftModBlocks.DOMAIN_STONE_BRICKS);
      CURSED_BLOCK = block(JujutsucraftModBlocks.CURSED_BLOCK);
      DRAGON_BONE = REGISTRY.register("dragon_bone", () -> new DragonBoneItem());
      CURSED_SPIRIT_GRADE_24_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_24_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_24, -3355444, -3355444, new Item.Properties()));
      CURSED_SPIRIT_GRADE_14_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_14_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_14, -6710887, -6710887, new Item.Properties()));
      COCKROACHES_SPAWN_EGG = REGISTRY.register("cockroaches_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.COCKROACHES, -16777216, -16777216, new Item.Properties()));
      KILLER_1_SPAWN_EGG = REGISTRY.register("killer_1_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.KILLER_1, -3355444, -3355444, new Item.Properties()));
      JOGO_SPAWN_EGG = REGISTRY.register("jogo_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.JOGO, -16724992, -10079488, new Item.Properties()));
      CURSED_SPIRIT_GRADE_15_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_15_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_15, -6710887, -6710887, new Item.Properties()));
      CURSED_SPIRIT_GRADE_22_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_22_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_22, -3355444, -3355444, new Item.Properties()));
      TAKADA_SPAWN_EGG = REGISTRY.register("takada_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.TAKADA, -14805760, -47509, new Item.Properties()));
      CLOTHES_URAUME_HELMET = REGISTRY.register("clothes_uraume_helmet", () -> new ClothesUraumeItem.Helmet());
      CLOTHES_URAUME_CHESTPLATE = REGISTRY.register("clothes_uraume_chestplate", () -> new ClothesUraumeItem.Chestplate());
      CLOTHES_URAUME_LEGGINGS = REGISTRY.register("clothes_uraume_leggings", () -> new ClothesUraumeItem.Leggings());
      CLOTHES_URAUME_BOOTS = REGISTRY.register("clothes_uraume_boots", () -> new ClothesUraumeItem.Boots());
      GAVEL = REGISTRY.register("gavel", () -> new GavelItem());
      DOMAIN_ICE = block(JujutsucraftModBlocks.DOMAIN_ICE);
      UNIFORM_ITADORI_CHESTPLATE = REGISTRY.register("uniform_itadori_chestplate", () -> new UniformItadoriItem.Chestplate());
      UNIFORM_ITADORI_LEGGINGS = REGISTRY.register("uniform_itadori_leggings", () -> new UniformItadoriItem.Leggings());
      CURSED_SPIRIT_GRADE_25_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_25_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_25, -3355444, -3355444, new Item.Properties()));
      CURSED_SPIRIT_GRADE_02_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_02_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_02, -10066330, -10066330, new Item.Properties()));
      CURSED_SPIRIT_GRADE_03_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_03_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_03, -10066330, -10066330, new Item.Properties()));
      CURSED_SPIRIT_GRADE_05_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_05_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_05, -10066330, -10066330, new Item.Properties()));
      CURSED_SPIRIT_GRADE_16_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_16_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_16, -6710887, -6710887, new Item.Properties()));
      BATHYNOMUS_GIGANTEUS_SPAWN_EGG = REGISTRY.register("bathynomus_giganteus_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.BATHYNOMUS_GIGANTEUS, -3355444, -3355444, new Item.Properties()));
      ITEM_MASTER_FALLING_BLOSSOM_EMOTION = REGISTRY.register("item_master_falling_blossom_emotion", () -> new ItemMasterFallingBlossomEmotionItem());
      MERGED_BEAST_AGITO_SPAWN_EGG = REGISTRY.register("merged_beast_agito_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.MERGED_BEAST_AGITO, -16777216, -16777216, new Item.Properties()));
      SICKLE = REGISTRY.register("sickle", () -> new SickleItem());
      DOMAIN_BLOOD = block(JujutsucraftModBlocks.DOMAIN_BLOOD);
      CURSED_SPIRIT_GRADE_313_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_313_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_313, -1, -1, new Item.Properties()));
      CURSED_SPIRIT_GRADE_314_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_314_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_314, -1, -1, new Item.Properties()));
      CURSED_SPIRIT_GRADE_315_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_315_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_315, -1, -1, new Item.Properties()));
      CURSED_SPIRIT_GRADE_316_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_316_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_316, -1, -1, new Item.Properties()));
      CURSED_SPIRIT_GRADE_317_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_317_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_317, -1, -1, new Item.Properties()));
      CURSED_SPIRIT_GRADE_318_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_318_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_318, -1, -1, new Item.Properties()));
      CURSED_SPIRIT_GRADE_26_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_26_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_26, -3355444, -3355444, new Item.Properties()));
      CURSED_SPIRIT_GRADE_27_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_27_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_27, -3355444, -3355444, new Item.Properties()));
      CURSED_SPIRIT_GRADE_28_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_28_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_28, -3355444, -3355444, new Item.Properties()));
      CURSED_SPIRIT_GRADE_29_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_29_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_29, -3355444, -3355444, new Item.Properties()));
      CURSED_SPIRIT_GRADE_21_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_21_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_21, -3355444, -3355444, new Item.Properties()));
      CLOTHES_NANAMI_HELMET = REGISTRY.register("clothes_nanami_helmet", () -> new ClothesNanamiItem.Helmet());
      CLOTHES_NANAMI_CHESTPLATE = REGISTRY.register("clothes_nanami_chestplate", () -> new ClothesNanamiItem.Chestplate());
      CLOTHES_NANAMI_LEGGINGS = REGISTRY.register("clothes_nanami_leggings", () -> new ClothesNanamiItem.Leggings());
      CLOTHES_SUKUNA_FUSHIGURO_CHESTPLATE = REGISTRY.register("clothes_sukuna_fushiguro_chestplate", () -> new ClothesSukunaFushiguroItem.Chestplate());
      CLOTHES_ZENIN_NAOBITO_CHESTPLATE = REGISTRY.register("clothes_zenin_naobito_chestplate", () -> new ClothesZeninNaobitoItem.Chestplate());
      CLOTHES_CHOSO_HELMET = REGISTRY.register("clothes_choso_helmet", () -> new ClothesChosoItem.Helmet());
      CLOTHES_CHOSO_CHESTPLATE = REGISTRY.register("clothes_choso_chestplate", () -> new ClothesChosoItem.Chestplate());
      CLOTHES_JOGO_HELMET = REGISTRY.register("clothes_jogo_helmet", () -> new ClothesJogoItem.Helmet());
      CLOTHES_JOGO_CHESTPLATE = REGISTRY.register("clothes_jogo_chestplate", () -> new ClothesJogoItem.Chestplate());
      CLAWS = REGISTRY.register("claws", () -> new ClawsItem());
      CURSED_SPIRIT_GRADE_18_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_18_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_18, -6710887, -6710887, new Item.Properties()));
      SCISSORS = REGISTRY.register("scissors", () -> new ScissorsItem());
      CURSED_SPIRIT_GRADE_06_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_06_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_06, -10066330, -10066330, new Item.Properties()));
      CURSED_SPIRIT_GRADE_07_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_07_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_07, -10066330, -10066330, new Item.Properties()));
      CURSED_SPIRIT_GRADE_08_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_08_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_08, -10066330, -10066330, new Item.Properties()));
      COPIED_CURSED_TECHNIQUE = REGISTRY.register("copied_cursed_technique", () -> new CopiedCursedTechniqueItem());
      RIKA_2_SPAWN_EGG = REGISTRY.register("rika_2_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.RIKA_2, -10066330, -10066330, new Item.Properties()));
      RIKA_SPAWN_EGG = REGISTRY.register("rika_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.RIKA, -10066330, -10066330, new Item.Properties()));
      ITEM_MASTER_DOMAIN_AMPLIFICATION = REGISTRY.register("item_master_domain_amplification", () -> new ItemMasterDomainAmplificationItem());
      DOMAIN_PLANKS = block(JujutsucraftModBlocks.DOMAIN_PLANKS);
      EXECUTIONERS_SWORD = REGISTRY.register("executioners_sword", () -> new ExecutionersSwordItem());
      GAVEL_LONG = REGISTRY.register("gavel_long", () -> new GavelLongItem());
      GAVEL_BIG = REGISTRY.register("gavel_big", () -> new GavelBigItem());
      UNIFORM_HIGURUMA_CHESTPLATE = REGISTRY.register("uniform_higuruma_chestplate", () -> new UniformHigurumaItem.Chestplate());
      UNIFORM_HIGURUMA_LEGGINGS = REGISTRY.register("uniform_higuruma_leggings", () -> new UniformHigurumaItem.Leggings());
      TOAD_SPAWN_EGG = REGISTRY.register("toad_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.TOAD, -16777216, -16777216, new Item.Properties()));
      TODO_AOI_SPAWN_EGG = REGISTRY.register("todo_aoi_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.TODO_AOI, -26317, -16777216, new Item.Properties()));
      EIGHT_HANDLED_SWROD_DIVERGENT_SILA_DIVINE_GENERAL_MAHORAGA_SPAWN_EGG = REGISTRY.register("eight_handled_swrod_divergent_sila_divine_general_mahoraga_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.EIGHT_HANDLED_SWROD_DIVERGENT_SILA_DIVINE_GENERAL_MAHORAGA, -16777216, -16777216, new Item.Properties()));
      TRUCK_SPAWN_EGG = REGISTRY.register("truck_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.TRUCK, -1, -1, new Item.Properties()));
      CLOTHES_ANGEL_HELMET = REGISTRY.register("clothes_angel_helmet", () -> new ClothesAngelItem(Type.HELMET, new Item.Properties()));
      CLOTHES_ANGEL_CHESTPLATE = REGISTRY.register("clothes_angel_chestplate", () -> new ClothesAngelItem(Type.CHESTPLATE, new Item.Properties()));
      CLOTHES_DAGON_HELMET = REGISTRY.register("clothes_dagon_helmet", () -> new ClothesDagonItem(Type.HELMET, new Item.Properties()));
      CLOTHES_DAGON_CHESTPLATE = REGISTRY.register("clothes_dagon_chestplate", () -> new ClothesDagonItem(Type.CHESTPLATE, new Item.Properties()));
      KNIFE = REGISTRY.register("knife", () -> new KnifeItem());
      SWORD_SHIGEMO = REGISTRY.register("sword_shigemo", () -> new SwordShigemoItem());
      HAMMER = REGISTRY.register("hammer", () -> new HammerItem());
      DOMAIN_PODZOL = block(JujutsucraftModBlocks.DOMAIN_PODZOL);
      COCKROACH_LARVA_SPAWN_EGG = REGISTRY.register("cockroach_larva_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.COCKROACH_LARVA, -3355444, -3355444, new Item.Properties()));
      CLOTHES_KUSAKABE_CHESTPLATE = REGISTRY.register("clothes_kusakabe_chestplate", () -> new ClothesKusakabeItem(Type.CHESTPLATE, new Item.Properties()));
      CLOTHES_KUSAKABE_LEGGINGS = REGISTRY.register("clothes_kusakabe_leggings", () -> new ClothesKusakabeItem(Type.LEGGINGS, new Item.Properties()));
      URO_TAKAKO_SPAWN_EGG = REGISTRY.register("uro_takako_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.URO_TAKAKO, -65281, -26113, new Item.Properties()));
      CLOTHES_URO_HELMET = REGISTRY.register("clothes_uro_helmet", () -> new ClothesUroItem(Type.HELMET, new Item.Properties()));
      CLOTHES_URO_CHESTPLATE = REGISTRY.register("clothes_uro_chestplate", () -> new ClothesUroItem(Type.CHESTPLATE, new Item.Properties()));
      CLOTHES_KIRARA_HELMET = REGISTRY.register("clothes_kirara_helmet", () -> new ClothesKiraraItem.Helmet());
      CLOTHES_KIRARA_CHESTPLATE = REGISTRY.register("clothes_kirara_chestplate", () -> new ClothesKiraraItem.Chestplate());
      CLOTHES_HAKARI_KINJI_HELMET = REGISTRY.register("clothes_hakari_kinji_helmet", () -> new ClothesHakariKinjiItem.Helmet());
      CLOTHES_HAKARI_KINJI_CHESTPLATE = REGISTRY.register("clothes_hakari_kinji_chestplate", () -> new ClothesHakariKinjiItem.Chestplate());
      CLOTHES_HAKARI_KINJI_LEGGINGS = REGISTRY.register("clothes_hakari_kinji_leggings", () -> new ClothesHakariKinjiItem.Leggings());
      CLOTHES_HAKARI_KINJI_BOOTS = REGISTRY.register("clothes_hakari_kinji_boots", () -> new ClothesHakariKinjiItem.Boots());
      OGAMI_SPAWN_EGG = REGISTRY.register("ogami_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.OGAMI, -3355444, -6710887, new Item.Properties()));
      DOMAIN_WHITE = block(JujutsucraftModBlocks.DOMAIN_WHITE);
      BULLET_BALL = REGISTRY.register("bullet_ball", () -> new BulletBallItem());
      CLOTHES_NISHIMIYA_HELMET = REGISTRY.register("clothes_nishimiya_helmet", () -> new ClothesNishimiyaItem.Helmet());
      CLOTHES_MIGUEL_HELMET = REGISTRY.register("clothes_miguel_helmet", () -> new ClothesMiguelItem.Helmet());
      CLOTHES_MIGUEL_CHESTPLATE = REGISTRY.register("clothes_miguel_chestplate", () -> new ClothesMiguelItem.Chestplate());
      CLOTHES_MIGUEL_LEGGINGS = REGISTRY.register("clothes_miguel_leggings", () -> new ClothesMiguelItem.Leggings());
      CLOTHES_MIGUEL_BOOTS = REGISTRY.register("clothes_miguel_boots", () -> new ClothesMiguelItem.Boots());
      UNIFORM_Q_HELMET = REGISTRY.register("uniform_q_helmet", () -> new UniformQItem.Helmet());
      UNIFORM_Q_CHESTPLATE = REGISTRY.register("uniform_q_chestplate", () -> new UniformQItem.Chestplate());
      UNIFORM_Q_LEGGINGS = REGISTRY.register("uniform_q_leggings", () -> new UniformQItem.Leggings());
      SWORD_KUSAKABE = REGISTRY.register("sword_kusakabe", () -> new SwordKusakabeItem());
      MIGUEL_DANCER_SPAWN_EGG = REGISTRY.register("miguel_dancer_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.MIGUEL_DANCER, -1, -10092442, new Item.Properties()));
      CLOTHES_YOROZU_CHESTPLATE = REGISTRY.register("clothes_yorozu_chestplate", () -> new ClothesYorozuItem.Chestplate());
      ROZETSU_SPAWN_EGG = REGISTRY.register("rozetsu_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.ROZETSU, -16751104, -10066330, new Item.Properties()));
      ZENIN_CHOJURO_SPAWN_EGG = REGISTRY.register("zenin_chojuro_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.ZENIN_CHOJURO, -16777216, -13210, new Item.Properties()));
      G_STAFF = REGISTRY.register("g_staff", () -> new GStaffItem());
      CURSED_SPIRIT_GRADE_319_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_319_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_319, -1, -1, new Item.Properties()));
      CURSED_SPIRIT_GRADE_210_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_210_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_210, -3355444, -3355444, new Item.Properties()));
      CURSED_SPIRIT_GRADE_211_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_211_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_211, -3355444, -3355444, new Item.Properties()));
      CURSED_SPIRIT_GRADE_212_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_212_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_212, -3355444, -3355444, new Item.Properties()));
      MOON_DREGS_SPAWN_EGG = REGISTRY.register("moon_dregs_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.MOON_DREGS, -3342337, -52, new Item.Properties()));
      SWORD_OPTION = REGISTRY.register("sword_option", () -> new SwordOptionItem());
      PANDA_NORMAL_SPAWN_EGG = REGISTRY.register("panda_normal_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.PANDA_NORMAL, -1, -16777216, new Item.Properties()));
      DOLL_1_SPAWN_EGG = REGISTRY.register("doll_1_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.DOLL_1, -6711040, -6711040, new Item.Properties()));
      ITEM_DOLL = REGISTRY.register("item_doll", () -> new ItemDollItem());
      ITADORI_ARM = REGISTRY.register("itadori_arm", () -> new ItadoriArmItem());
      BROOM = REGISTRY.register("broom", () -> new BroomItem());
      ENTITY_BROOM_SPAWN_EGG = REGISTRY.register("entity_broom_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.ENTITY_BROOM, -13210, -13210, new Item.Properties()));
      NAIL = REGISTRY.register("nail", () -> new NailItem());
      SHIKIGAMI_HETEROCEPHALUS_GLABER_SPAWN_EGG = REGISTRY.register("shikigami_heterocephalus_glaber_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.SHIKIGAMI_HETEROCEPHALUS_GLABER, -13108, -52429, new Item.Properties()));
      SHIKIGAMI_PTEROSAUR_SPAWN_EGG = REGISTRY.register("shikigami_pterosaur_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.SHIKIGAMI_PTEROSAUR, -10066330, -6710887, new Item.Properties()));
      DHRUV_LAKDAWALLA_SPAWN_EGG = REGISTRY.register("dhruv_lakdawalla_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.DHRUV_LAKDAWALLA, -52, -39322, new Item.Properties()));
      DOMAIN = block(JujutsucraftModBlocks.DOMAIN);
      CURSED_SPIRIT_GRADE_110_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_110_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_110, -6710887, -6710887, new Item.Properties()));
      CURSED_SPIRIT_GRADE_09_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_09_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_09, -10066330, -10066330, new Item.Properties()));
      CLOTHES_REGGIE_STAR_CHESTPLATE = REGISTRY.register("clothes_reggie_star_chestplate", () -> new ClothesReggieStarItem.Chestplate());
      INSECT_ARMOR_HELMET = REGISTRY.register("insect_armor_helmet", () -> new InsectArmorItem(Type.HELMET, new Item.Properties()));
      INSECT_ARMOR_CHESTPLATE = REGISTRY.register("insect_armor_chestplate", () -> new InsectArmorItem(Type.CHESTPLATE, new Item.Properties()));
      INSECT_ARMOR_LEGGINGS = REGISTRY.register("insect_armor_leggings", () -> new InsectArmorItem(Type.LEGGINGS, new Item.Properties()));
      CURSED_SPIRIT_GRADE_213_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_213_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_213, -3355444, -3355444, new Item.Properties()));
      CURSED_SPIRIT_GRADE_214_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_214_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_214, -3355444, -3355444, new Item.Properties()));
      CLOTHES_INO_TAKUMA_1_HELMET = REGISTRY.register("clothes_ino_takuma_1_helmet", () -> new ClothesInoTakuma1Item.Helmet());
      CLOTHES_INO_TAKUMA_1_CHESTPLATE = REGISTRY.register("clothes_ino_takuma_1_chestplate", () -> new ClothesInoTakuma1Item.Chestplate());
      CLOTHES_INO_TAKUMA_1_LEGGINGS = REGISTRY.register("clothes_ino_takuma_1_leggings", () -> new ClothesInoTakuma1Item.Leggings());
      CLOTHES_INO_TAKUMA_1_BOOTS = REGISTRY.register("clothes_ino_takuma_1_boots", () -> new ClothesInoTakuma1Item.Boots());
      CLOTHES_INO_TAKUMA_2_HELMET = REGISTRY.register("clothes_ino_takuma_2_helmet", () -> new ClothesInoTakuma2Item.Helmet());
      CURSED_SPIRIT_GRADE_321_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_321_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_321, -1, -1, new Item.Properties()));
      CURSED_SPIRIT_GRADE_322_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_322_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_322, -1, -1, new Item.Properties()));
      CURSED_SPIRIT_GRADE_215_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_215_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_215, -3355444, -3355444, new Item.Properties()));
      PISTOL = REGISTRY.register("pistol", () -> new PistolItem());
      CURSED_SPIRIT_GRADE_111_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_111_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_111, -6710887, -6710887, new Item.Properties()));
      CURSED_SPIRIT_GRADE_216_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_216_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_216, -3355444, -3355444, new Item.Properties()));
      ROZETSU_SHIKIGAMI_VESSEL_SPAWN_EGG = REGISTRY.register("rozetsu_shikigami_vessel_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.ROZETSU_SHIKIGAMI_VESSEL, -13108, -13108, new Item.Properties()));
      ROZETSU_SHIKIGAMI_VESSEL_2_SPAWN_EGG = REGISTRY.register("rozetsu_shikigami_vessel_2_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.ROZETSU_SHIKIGAMI_VESSEL_2, -13108, -13108, new Item.Properties()));
      CURSED_SPIRIT_GRADE_04_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_04_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_04, -10066330, -10066330, new Item.Properties()));
      HEAD_JET_HELMET = REGISTRY.register("head_jet_helmet", () -> new HeadJetItem(Type.HELMET, new Item.Properties()));
      HEAD_PROPELLER_HELMET = REGISTRY.register("head_propeller_helmet", () -> new HeadPropellerItem(Type.HELMET, new Item.Properties()));
      ITADORI_YUJI_SPAWN_EGG = REGISTRY.register("itadori_yuji_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.ITADORI_YUJI, -13159, -26266, new Item.Properties()));
      ITADORI_YUJI_SHIBUYA_SPAWN_EGG = REGISTRY.register("itadori_yuji_shibuya_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.ITADORI_YUJI_SHIBUYA, -13159, -26266, new Item.Properties()));
      ITADORI_YUJI_SHINJUKU_SPAWN_EGG = REGISTRY.register("itadori_yuji_shinjuku_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.ITADORI_YUJI_SHINJUKU, -13159, -26266, new Item.Properties()));
      FUSHIGURO_MEGUMI_SPAWN_EGG = REGISTRY.register("fushiguro_megumi_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.FUSHIGURO_MEGUMI, -16777216, -13421773, new Item.Properties()));
      FUSHIGURO_MEGUMI_SHIBUYA_SPAWN_EGG = REGISTRY.register("fushiguro_megumi_shibuya_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.FUSHIGURO_MEGUMI_SHIBUYA, -16777216, -13421773, new Item.Properties()));
      NOBARA_KUGISAKI_SPAWN_EGG = REGISTRY.register("nobara_kugisaki_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.NOBARA_KUGISAKI, -16777063, -39373, new Item.Properties()));
      INUMAKI_TOGE_SPAWN_EGG = REGISTRY.register("inumaki_toge_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.INUMAKI_TOGE, -1, -52, new Item.Properties()));
      ZENIN_MAKI_SPAWN_EGG = REGISTRY.register("zenin_maki_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.ZENIN_MAKI, -16751053, -16764160, new Item.Properties()));
      ZENIN_MAKI_CULLING_GAME_SPAWN_EGG = REGISTRY.register("zenin_maki_culling_game_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.ZENIN_MAKI_CULLING_GAME, -16751053, -16764160, new Item.Properties()));
      OKKOTSU_YUTA_SPAWN_EGG = REGISTRY.register("okkotsu_yuta_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.OKKOTSU_YUTA, -1, -3342388, new Item.Properties()));
      OKKOTSU_YUTA_CULLING_GAME_SPAWN_EGG = REGISTRY.register("okkotsu_yuta_culling_game_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.OKKOTSU_YUTA_CULLING_GAME, -1, -3342388, new Item.Properties()));
      HOSHI_KIRARA_SPAWN_EGG = REGISTRY.register("hoshi_kirara_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.HOSHI_KIRARA, -16777216, -52225, new Item.Properties()));
      HAKARI_KINJI_SPAWN_EGG = REGISTRY.register("hakari_kinji_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.HAKARI_KINJI, -3394561, -10092442, new Item.Properties()));
      YAGA_MASAMICHI_SPAWN_EGG = REGISTRY.register("yaga_masamichi_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.YAGA_MASAMICHI, -6724096, -10092544, new Item.Properties()));
      KUSAKABE_ATSUYA_SPAWN_EGG = REGISTRY.register("kusakabe_atsuya_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.KUSAKABE_ATSUYA, -26368, -26113, new Item.Properties()));
      MIWA_KASUMI_SPAWN_EGG = REGISTRY.register("miwa_kasumi_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.MIWA_KASUMI, -6697729, -6697729, new Item.Properties()));
      NISHIMIYA_MOMO_SPAWN_EGG = REGISTRY.register("nishimiya_momo_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.NISHIMIYA_MOMO, -103, -10066177, new Item.Properties()));
      KAMO_NORITOSHI_SPAWN_EGG = REGISTRY.register("kamo_noritoshi_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.KAMO_NORITOSHI, -16777216, -3407872, new Item.Properties()));
      MECHAMARU_SPAWN_EGG = REGISTRY.register("mechamaru_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.MECHAMARU, -6750208, -6750208, new Item.Properties()));
      GETO_SUGURU_SPAWN_EGG = REGISTRY.register("geto_suguru_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.GETO_SUGURU, -16777216, -10066330, new Item.Properties()));
      GETO_SUGURU_CURSE_USER_SPAWN_EGG = REGISTRY.register("geto_suguru_curse_user_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.GETO_SUGURU_CURSE_USER, -10027162, -154, new Item.Properties()));
      KENJAKU_SPAWN_EGG = REGISTRY.register("kenjaku_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.KENJAKU, -10027162, -154, new Item.Properties()));
      GOJO_SATORU_SCHOOL_DAYS_SPAWN_EGG = REGISTRY.register("gojo_satoru_school_days_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.GOJO_SATORU_SCHOOL_DAYS, -1, -6684673, new Item.Properties()));
      GOJO_SATORU_SPAWN_EGG = REGISTRY.register("gojo_satoru_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.GOJO_SATORU, -1, -6684673, new Item.Properties()));
      JUJUTSU_SORCERER_SPAWN_EGG = REGISTRY.register("jujutsu_sorcerer_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.JUJUTSU_SORCERER, -10079488, -10079488, new Item.Properties()));
      MEI_MEI_SPAWN_EGG = REGISTRY.register("mei_mei_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.MEI_MEI, -3355393, -3355393, new Item.Properties()));
      NANAMI_KENTO_SPAWN_EGG = REGISTRY.register("nanami_kento_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.NANAMI_KENTO, -1, -256, new Item.Properties()));
      TSUKUMO_YUKI_SPAWN_EGG = REGISTRY.register("tsukumo_yuki_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.TSUKUMO_YUKI, -256, -65536, new Item.Properties()));
      INO_TAKUMA_SPAWN_EGG = REGISTRY.register("ino_takuma_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.INO_TAKUMA, -16777216, -3394816, new Item.Properties()));
      ZENIN_NAOBITO_SPAWN_EGG = REGISTRY.register("zenin_naobito_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.ZENIN_NAOBITO, -16777216, -6710887, new Item.Properties()));
      ZENIN_NAOYA_SPAWN_EGG = REGISTRY.register("zenin_naoya_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.ZENIN_NAOYA, -16777216, -6711040, new Item.Properties()));
      ZENIN_JINICHI_SPAWN_EGG = REGISTRY.register("zenin_jinichi_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.ZENIN_JINICHI, -16777216, -10079488, new Item.Properties()));
      ZENIN_OGI_SPAWN_EGG = REGISTRY.register("zenin_ogi_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.ZENIN_OGI, -16777216, -65536, new Item.Properties()));
      YOSHINO_JUNPEI_SPAWN_EGG = REGISTRY.register("yoshino_junpei_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.YOSHINO_JUNPEI, -6750055, -6684673, new Item.Properties()));
      ZENIN_RANTA_SPAWN_EGG = REGISTRY.register("zenin_ranta_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.ZENIN_RANTA, -16777216, -3355444, new Item.Properties()));
      KUKURU_SPAWN_EGG = REGISTRY.register("kukuru_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.KUKURU, -10066330, -3355444, new Item.Properties()));
      FUSHIGURO_TOJI_SPAWN_EGG = REGISTRY.register("fushiguro_toji_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.FUSHIGURO_TOJI, -16777216, -16777114, new Item.Properties()));
      FUSHIGURO_TOJI_BUG_SPAWN_EGG = REGISTRY.register("fushiguro_toji_bug_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.FUSHIGURO_TOJI_BUG, -16777216, -65536, new Item.Properties()));
      CURSED_SPIRIT_GRADE_01_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_01_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_01, -10066330, -10066330, new Item.Properties()));
      CURSE_USER_SPAWN_EGG = REGISTRY.register("curse_user_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSE_USER, -10053121, -10053121, new Item.Properties()));
      CURSE_USER_1_SPAWN_EGG = REGISTRY.register("curse_user_1_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSE_USER_1, -3355444, -26317, new Item.Properties()));
      Q_SPAWN_EGG = REGISTRY.register("q_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.Q, -3355444, -10066330, new Item.Properties()));
      MIMIKO_SPAWN_EGG = REGISTRY.register("mimiko_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.MIMIKO, -16777114, -52429, new Item.Properties()));
      NANAKO_SPAWN_EGG = REGISTRY.register("nanako_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.NANAKO, -16777114, -52429, new Item.Properties()));
      NEGI_TOSHIHISA_SPAWN_EGG = REGISTRY.register("negi_toshihisa_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.NEGI_TOSHIHISA, -10066330, -3355444, new Item.Properties()));
      LARUE_SPAWN_EGG = REGISTRY.register("larue_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.LARUE, -1, -52, new Item.Properties()));
      MIGUEL_SPAWN_EGG = REGISTRY.register("miguel_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.MIGUEL, -1, -10092442, new Item.Properties()));
      KUMIYA_JUZO_SPAWN_EGG = REGISTRY.register("kumiya_juzo_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.KUMIYA_JUZO, -6737152, -16777216, new Item.Properties()));
      AWASAKA_JIRO_SPAWN_EGG = REGISTRY.register("awasaka_jiro_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.AWASAKA_JIRO, -1, -13159, new Item.Properties()));
      HANAMI_SPAWN_EGG = REGISTRY.register("hanami_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.HANAMI, -1, -3381760, new Item.Properties()));
      MAHITO_SPAWN_EGG = REGISTRY.register("mahito_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.MAHITO, -3355393, -16777114, new Item.Properties()));
      URAUME_SPAWN_EGG = REGISTRY.register("uraume_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.URAUME, -6684673, -52480, new Item.Properties()));
      SUKUNA_SPAWN_EGG = REGISTRY.register("sukuna_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.SUKUNA, -39373, -13434829, new Item.Properties()));
      SUKUNA_FUSHIGURO_SPAWN_EGG = REGISTRY.register("sukuna_fushiguro_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.SUKUNA_FUSHIGURO, -39373, -13434829, new Item.Properties()));
      SUKUNA_PERFECT_SPAWN_EGG = REGISTRY.register("sukuna_perfect_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.SUKUNA_PERFECT, -39373, -13434829, new Item.Properties()));
      ESO_SPAWN_EGG = REGISTRY.register("eso_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.ESO, -10092544, -16777114, new Item.Properties()));
      CHOSO_SPAWN_EGG = REGISTRY.register("choso_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CHOSO, -10092544, -16777114, new Item.Properties()));
      HABA_SPAWN_EGG = REGISTRY.register("haba_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.HABA, -3355444, -26113, new Item.Properties()));
      HANYU_SPAWN_EGG = REGISTRY.register("hanyu_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.HANYU, -3355444, -26113, new Item.Properties()));
      TAKABA_FUMIHIKO_SPAWN_EGG = REGISTRY.register("takaba_fumihiko_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.TAKABA_FUMIHIKO, -6710785, -103, new Item.Properties()));
      HIGURUMA_HIROMI_SPAWN_EGG = REGISTRY.register("higuruma_hiromi_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.HIGURUMA_HIROMI, -16777216, -16777216, new Item.Properties()));
      CHARLES_BERNARD_SPAWN_EGG = REGISTRY.register("charles_bernard_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CHARLES_BERNARD, -10040065, -6710785, new Item.Properties()));
      ISHIGORI_RYU_SPAWN_EGG = REGISTRY.register("ishigori_ryu_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.ISHIGORI_RYU, -16777216, -3355444, new Item.Properties()));
      KASHIMO_HAJIME_SPAWN_EGG = REGISTRY.register("kashimo_hajime_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.KASHIMO_HAJIME, -10027009, -52225, new Item.Properties()));
      KURUSU_HANA_SPAWN_EGG = REGISTRY.register("kurusu_hana_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.KURUSU_HANA, -52, -154, new Item.Properties()));
      HAZENOKI_SPAWN_EGG = REGISTRY.register("hazenoki_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.HAZENOKI, -103, -13421824, new Item.Properties()));
      REGGIE_STAR_SPAWN_EGG = REGISTRY.register("reggie_star_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.REGGIE_STAR, -103, -1, new Item.Properties()));
      DAIDO_HAGANE_SPAWN_EGG = REGISTRY.register("daido_hagane_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.DAIDO_HAGANE, -10079488, -3355444, new Item.Properties()));
      MIYO_ROKUJUSHI_SPAWN_EGG = REGISTRY.register("miyo_rokujushi_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.MIYO_ROKUJUSHI, -13108, -205, new Item.Properties()));
      YOROZU_SPAWN_EGG = REGISTRY.register("yorozu_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.YOROZU, -3355444, -26113, new Item.Properties()));
      ROZETSU_SHIKIGAMI_SPAWN_EGG = REGISTRY.register("rozetsu_shikigami_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.ROZETSU_SHIKIGAMI, -26266, -26266, new Item.Properties()));
      TRANSFIGURED_HUMAN_SPAWN_EGG = REGISTRY.register("transfigured_human_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.TRANSFIGURED_HUMAN, -6710887, -6710887, new Item.Properties()));
      POLYMORPHIC_SOUL_ISOMER_SPAWN_EGG = REGISTRY.register("polymorphic_soul_isomer_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.POLYMORPHIC_SOUL_ISOMER, -6710887, -6710887, new Item.Properties()));
      HANAMI_EYE_HELMET = REGISTRY.register("hanami_eye_helmet", () -> new HanamiEyeItem(Type.HELMET, new Item.Properties()));
      MYTHICAL_BEAST_AMBER_HELMET = REGISTRY.register("mythical_beast_amber_helmet", () -> new MythicalBeastAmberItem(Type.HELMET, (new Item.Properties()).m_41486_()));
      ITADORI_YUJI_PAPER_HELMET = REGISTRY.register("itadori_yuji_paper_helmet", () -> new ItadoriYujiPaperItem(Type.HELMET, new Item.Properties()));
      ZENIN_NAOYA_CURSED_SPIRIT_SPAWN_EGG = REGISTRY.register("zenin_naoya_cursed_spirit_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.ZENIN_NAOYA_CURSED_SPIRIT, -10092442, -154, new Item.Properties()));
      DAGON_SPAWN_EGG = REGISTRY.register("dagon_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.DAGON, -65536, -16777216, new Item.Properties()));
      SHIGEMO_HARUTA_SPAWN_EGG = REGISTRY.register("shigemo_haruta_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.SHIGEMO_HARUTA, -16777216, -205, new Item.Properties()));
      ORCASAN_SPAWN_EGG = REGISTRY.register("orcasan_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.ORCASAN, -16777216, -3355444, new Item.Properties()));
      PLAYFUL_CLOUD = REGISTRY.register("playful_cloud", () -> new PlayfulCloudItem());
      BLACK_ROPE = REGISTRY.register("black_rope", () -> new BlackRopeItem());
      MAHITO_HAND_1 = REGISTRY.register("mahito_hand_1", () -> new MahitoHand1Item());
      DEATH_PAINTING = REGISTRY.register("death_painting", () -> new DeathPaintingItem());
      DOMAIN_DARK_STONE = block(JujutsucraftModBlocks.DOMAIN_DARK_STONE);
      DIVINE_DOG_TOTALITY_SPAWN_EGG = REGISTRY.register("divine_dog_totality_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.DIVINE_DOG_TOTALITY, -16777216, -16777216, new Item.Properties()));
      NUE_SPAWN_EGG = REGISTRY.register("nue_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.NUE, -16777216, -16777216, new Item.Properties()));
      TIGER_FUNERAL_SPAWN_EGG = REGISTRY.register("tiger_funeral_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.TIGER_FUNERAL, -16777216, -16777216, new Item.Properties()));
      CURSED_SPIRIT_GRADE_010_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_010_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_010, -10066330, -10066330, new Item.Properties()));
      CAR_SPAWN_EGG = REGISTRY.register("car_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CAR, -1, -1, new Item.Properties()));
      CURSED_SPIRIT_GRADE_323_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_323_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_323, -1, -1, new Item.Properties()));
      CURSED_SPIRIT_GRADE_19_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_19_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_19, -6710887, -6710887, new Item.Properties()));
      CURSED_SPIRIT_GRADE_12_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_12_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_12, -6710887, -6710887, new Item.Properties()));
      CURSED_SPIRIT_GRADE_011_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_011_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_011, -10066330, -10066330, new Item.Properties()));
      CURSED_SPIRIT_GRADE_012_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_012_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_012, -10066330, -10066330, new Item.Properties()));
      CURSED_SPIRIT_GRADE_11_SPAWN_EGG = REGISTRY.register("cursed_spirit_grade_11_spawn_egg", () -> new ForgeSpawnEggItem(JujutsucraftModEntities.CURSED_SPIRIT_GRADE_11, -6710887, -6710887, new Item.Properties()));
   }
}
