package org.imgaine.gaigegaigekaigecraft.init;

import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.CreativeModeTabs;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.ItemLike;
import net.minecraft.world.level.block.Block;
import net.minecraftforge.event.BuildCreativeModeTabContentsEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod.EventBusSubscriber;
import net.minecraftforge.fml.common.Mod.EventBusSubscriber.Bus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.RegistryObject;

@EventBusSubscriber(
   bus = Bus.MOD
)
public class JujutsucraftModTabs {
   public static final DeferredRegister<CreativeModeTab> REGISTRY;
   public static final RegistryObject<CreativeModeTab> JUJUTSU_CRAFT;
   public static final RegistryObject<CreativeModeTab> JUJUTSU_CRAFT_JUJUTSU_SORCERER;
   public static final RegistryObject<CreativeModeTab> JUJUTSU_CRAFT_CURSED_SPIRITS;
   public static final RegistryObject<CreativeModeTab> JUJUTSU_CRAFT_OTHER_ENTITIES;
   public static final RegistryObject<CreativeModeTab> JUJUTSUCRAFT_WEAPONS;
   public static final RegistryObject<CreativeModeTab> JUJUTSUCRAFT_ARMORS;

   public JujutsucraftModTabs() {
   }

   @SubscribeEvent
   public static void buildTabContentsVanilla(BuildCreativeModeTabContentsEvent tabData) {
      if (tabData.getTabKey() == CreativeModeTabs.f_256788_) {
         tabData.m_246326_(((Block)JujutsucraftModBlocks.SCHOOL_BELL.get()).m_5456_());
      }

   }

   static {
      REGISTRY = DeferredRegister.create(Registries.f_279569_, "jujutsucraft");
      JUJUTSU_CRAFT = REGISTRY.register("jujutsu_craft", () -> CreativeModeTab.builder().m_257941_(Component.m_237115_("item_group.jujutsucraft.jujutsu_craft")).m_257737_(() -> new ItemStack((ItemLike)JujutsucraftModItems.CURSED_TECHNIQUE_CHANGER.get())).m_257501_((parameters, tabData) -> {
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_TECHNIQUE_CHANGER.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.ITEM_MASTER_SIX_EYES.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.ITEM_MASTER_PHYSICAL_GIFTED.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.ITEM_MASTER_SIMPLE_DOMAIN.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.ITEM_MASTER_FALLING_BLOSSOM_EMOTION.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.ITEM_MASTER_DOMAIN_EXPANSION.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.ITEM_MASTER_DOMAIN_AMPLIFICATION.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.ITEM_MASTER_REVERSE_CURSED_TECHNIQUE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.ITEM_INSECT.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.RECOMMENDATION_1.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.RECOMMENDATION_2.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_TECHNIQUE_STARTER.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.LOUDSPEAKER.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_BALL.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.DEATH_PAINTING.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.SUKUNA_FINGER.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.ITEM_DOLL.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.NAIL.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.PENDANT_TODO_AOI.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.BULLET_BALL.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.HUMAN_STOCK.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.HUMAN_STOCK_CAR.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.STEVENSON_SCREEN_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.DOLL_1_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CAR_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.TRUCK_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.ENTITY_BROOM_SPAWN_EGG.get());
         }).m_257652_());
      JUJUTSU_CRAFT_JUJUTSU_SORCERER = REGISTRY.register("jujutsu_craft_jujutsu_sorcerer", () -> CreativeModeTab.builder().m_257941_(Component.m_237115_("item_group.jujutsucraft.jujutsu_craft_jujutsu_sorcerer")).m_257737_(() -> new ItemStack(Items.f_42599_)).m_257501_((parameters, tabData) -> {
            tabData.m_246326_((ItemLike)JujutsucraftModItems.JUJUTSU_SORCERER_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.GETO_SUGURU_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.GOJO_SATORU_SCHOOL_DAYS_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.GOJO_SATORU_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.ITADORI_YUJI_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.ITADORI_YUJI_SHIBUYA_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.ITADORI_YUJI_SHINJUKU_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.FUSHIGURO_MEGUMI_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.FUSHIGURO_MEGUMI_SHIBUYA_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.NOBARA_KUGISAKI_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.INUMAKI_TOGE_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.PANDA_NORMAL_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.ZENIN_MAKI_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.ZENIN_MAKI_CULLING_GAME_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.OKKOTSU_YUTA_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.OKKOTSU_YUTA_CULLING_GAME_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.HOSHI_KIRARA_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.HAKARI_KINJI_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.YAGA_MASAMICHI_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.MIWA_KASUMI_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.NISHIMIYA_MOMO_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.KAMO_NORITOSHI_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.MECHAMARU_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.TODO_AOI_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.KUSAKABE_ATSUYA_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.MEI_MEI_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.INO_TAKUMA_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.NANAMI_KENTO_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.TSUKUMO_YUKI_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.KUKURU_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.ZENIN_RANTA_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.ZENIN_OGI_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.ZENIN_JINICHI_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.ZENIN_CHOJURO_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.ZENIN_NAOYA_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.ZENIN_NAOBITO_SPAWN_EGG.get());
         }).withTabsBefore(new ResourceLocation[]{JUJUTSU_CRAFT.getId()}).m_257652_());
      JUJUTSU_CRAFT_CURSED_SPIRITS = REGISTRY.register("jujutsu_craft_cursed_spirits", () -> CreativeModeTab.builder().m_257941_(Component.m_237115_("item_group.jujutsucraft.jujutsu_craft_cursed_spirits")).m_257737_(() -> new ItemStack(Items.f_42623_)).m_257501_((parameters, tabData) -> {
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_31_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_32_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_33_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_34_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_35_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_36_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_37_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_38_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_39_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_310_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_311_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_312_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_313_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_314_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_315_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_316_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_317_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_318_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_319_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_321_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_322_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_323_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_21_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_22_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_23_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_24_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_25_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_26_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_27_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_28_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_29_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_210_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_211_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_212_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_213_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_214_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_215_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_216_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_11_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_12_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_13_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_14_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_15_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_16_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_18_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_19_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_110_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_111_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.RIKA_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_01_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_02_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_03_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_04_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_05_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_06_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_07_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_08_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_09_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_010_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_011_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_GRADE_012_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.ROZETSU_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSE_USER_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSE_USER_1_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.Q_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.MIMIKO_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.NANAKO_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.NEGI_TOSHIHISA_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.LARUE_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.MIGUEL_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.MIGUEL_DANCER_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.GETO_SUGURU_CURSE_USER_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.SHIGEMO_HARUTA_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.KUMIYA_JUZO_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.AWASAKA_JIRO_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.OGAMI_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.HANAMI_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.DAGON_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.JOGO_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.MAHITO_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.KENJAKU_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.ZENIN_NAOYA_CURSED_SPIRIT_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.URAUME_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.SUKUNA_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.SUKUNA_FUSHIGURO_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.SUKUNA_PERFECT_SPAWN_EGG.get());
         }).withTabsBefore(new ResourceLocation[]{JUJUTSU_CRAFT_JUJUTSU_SORCERER.getId()}).m_257652_());
      JUJUTSU_CRAFT_OTHER_ENTITIES = REGISTRY.register("jujutsu_craft_other_entities", () -> CreativeModeTab.builder().m_257941_(Component.m_237115_("item_group.jujutsucraft.jujutsu_craft_other_entities")).m_257737_(() -> new ItemStack(Items.f_42564_)).m_257501_((parameters, tabData) -> {
            tabData.m_246326_((ItemLike)JujutsucraftModItems.FUSHIGURO_TOJI_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.FUSHIGURO_TOJI_BUG_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.YOSHINO_JUNPEI_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.KECHIZU_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.ESO_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CHOSO_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.HABA_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.HANYU_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.HAZENOKI_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.REGGIE_STAR_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.TAKABA_FUMIHIKO_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.KURUSU_HANA_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.HIGURUMA_HIROMI_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.DHRUV_LAKDAWALLA_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.URO_TAKAKO_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.ISHIGORI_RYU_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.DAIDO_HAGANE_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.MIYO_ROKUJUSHI_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CHARLES_BERNARD_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.KASHIMO_HAJIME_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.YOROZU_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.DIVINE_DOG_WHITE_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.DIVINE_DOG_BLACK_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.DIVINE_DOG_TOTALITY_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.NUE_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.MERGED_BEAST_AGITO_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.GREAT_SERPENT_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.TOAD_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.MAX_ELEPHANT_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.RABBIT_ESCAPE_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.ROUND_DEER_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.PIERCING_OX_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.TIGER_FUNERAL_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.EIGHT_HANDLED_SWROD_DIVERGENT_SILA_DIVINE_GENERAL_MAHORAGA_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.RIKA_2_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CROW_SPAWN_EGG.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.TRANSFIGURED_HUMAN_SPAWN_EGG.get());
         }).withTabsBefore(new ResourceLocation[]{JUJUTSU_CRAFT_CURSED_SPIRITS.getId()}).m_257652_());
      JUJUTSUCRAFT_WEAPONS = REGISTRY.register("jujutsucraft_weapons", () -> CreativeModeTab.builder().m_257941_(Component.m_237115_("item_group.jujutsucraft.jujutsucraft_weapons")).m_257737_(() -> new ItemStack((ItemLike)JujutsucraftModItems.SLAUGHTER_DEMON.get())).m_257501_((parameters, tabData) -> {
            tabData.m_246326_((ItemLike)JujutsucraftModItems.HAMMER.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.SLAUGHTER_DEMON.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.SWORD_OKKOTSU_YUTA.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.SWORD_BLACK.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.NAGINATA.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.WEAPON_NANAMI.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.NYOI_STAFF.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.MEI_MEI_AXE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.SWORD_OGI.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.BLAZING_COURAGE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.SWORD_MIWA_KASUMI.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.PISTOL.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.MAHITO_HAND_1.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.MAHITO_HAND_2.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.HANAMI_HAND.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.HARISEN.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.FESTER_LIFE_BLADE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.GARUDA_ITEM_BALL.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.GARUDA_ITEM.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.DRAGON_BONE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.SICKLE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLAWS.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.SCISSORS.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.KNIFE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.SWORD_SHIGEMO.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.SWORD_KUSAKABE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.G_STAFF.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.SWORD_OPTION.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.ITADORI_ARM.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.BROOM.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.INVERTED_SPEAR_OF_HEAVEN.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.SPLIT_SOUL_KATANA.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.BLACK_ROPE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.PLAYFUL_CLOUD.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.SWORD_OF_EXTERMINATION.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.SUPREME_MARTIAL_SOLUTION.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.HITEN.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.GAVEL.get());
         }).withTabsBefore(new ResourceLocation[]{JUJUTSU_CRAFT_OTHER_ENTITIES.getId()}).m_257652_());
      JUJUTSUCRAFT_ARMORS = REGISTRY.register("jujutsucraft_armors", () -> CreativeModeTab.builder().m_257941_(Component.m_237115_("item_group.jujutsucraft.jujutsucraft_armors")).m_257737_(() -> new ItemStack((ItemLike)JujutsucraftModItems.UNIFORM_NORMAL_CHESTPLATE.get())).m_257501_((parameters, tabData) -> {
            tabData.m_246326_((ItemLike)JujutsucraftModItems.UNIFORM_NORMAL_HELMET.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.UNIFORM_NORMAL_CHESTPLATE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.UNIFORM_NORMAL_LEGGINGS.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.UNIFORM_NORMAL_BOOTS.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.UNIFORM_ITADORI_CHESTPLATE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.UNIFORM_ITADORI_LEGGINGS.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.HAIR_FUSHIGURO_MEGUMI_HELMET.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.GLASSES_MAKI_HELMET.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.GLASSES_MAKI_CHESTPLATE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.GLASSES_MAKI_LEGGINGS.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.UNIFORM_OKKOTSU_CHESTPLATE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_HAKARI_KINJI_HELMET.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_HAKARI_KINJI_CHESTPLATE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_HAKARI_KINJI_LEGGINGS.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_HAKARI_KINJI_BOOTS.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_KIRARA_HELMET.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_KIRARA_CHESTPLATE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.SUNGLASSES_HELMET.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.BLINDFOLD_BANDAGE_HELMET.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.UNIFORM_GOJO_HELMET.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.UNIFORM_GOJO_CHESTPLATE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.UNIFORM_GOJO_LEGGINGS.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.UNIFORM_GOJO_BOOTS.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_DECISIVE_BATTLE_HELMET.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_DECISIVE_BATTLE_CHESTPLATE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_DECISIVE_BATTLE_LEGGINGS.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_KUSAKABE_CHESTPLATE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_KUSAKABE_LEGGINGS.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_NISHIMIYA_HELMET.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.MUSCULAR_BODY_CHESTPLATE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_TODO_AOI_LEGGINGS.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.UNIFORM_Q_HELMET.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.UNIFORM_Q_CHESTPLATE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.UNIFORM_Q_LEGGINGS.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.UNIFORM_GETO_LEGGINGS.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_FUSHIGURO_TOJI_CHESTPLATE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_FUSHIGURO_TOJI_LEGGINGS.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CURSED_SPIRIT_ARMOURY_CHESTPLATE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_GETO_HELMET.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_GETO_CHESTPLATE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_GETO_LEGGINGS.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_GETO_BOOTS.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_MIGUEL_HELMET.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_MIGUEL_CHESTPLATE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_MIGUEL_LEGGINGS.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_MIGUEL_BOOTS.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_NANAMI_HELMET.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_NANAMI_CHESTPLATE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_NANAMI_LEGGINGS.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_INO_TAKUMA_1_HELMET.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_INO_TAKUMA_1_CHESTPLATE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_INO_TAKUMA_1_LEGGINGS.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_INO_TAKUMA_1_BOOTS.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_INO_TAKUMA_2_HELMET.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_ZENIN_CHESTPLATE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_ZENIN_LEGGINGS.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_ZENIN_BOOTS.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_ZENIN_2_CHESTPLATE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_ZENIN_2_LEGGINGS.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_ZENIN_NAOBITO_CHESTPLATE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.RIKA_BODY_HELMET.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.RIKA_BODY_CHESTPLATE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.KUROURUSHI_BODY_HELMET.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.KUROURUSHI_BODY_CHESTPLATE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.KUROURUSHI_BODY_LEGGINGS.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.NAOYA_CURSED_SPIRIT_BODY_CHESTPLATE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.WING_KING_CHESTPLATE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_CHOSO_HELMET.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_CHOSO_CHESTPLATE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.HANAMI_EYE_HELMET.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_DAGON_HELMET.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_DAGON_CHESTPLATE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_JOGO_HELMET.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_JOGO_CHESTPLATE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.ARMOR_INSTANT_SPIRIT_BODYOF_DISTORTED_KILLING_HELMET.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.ARMOR_INSTANT_SPIRIT_BODYOF_DISTORTED_KILLING_CHESTPLATE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.ARMOR_INSTANT_SPIRIT_BODYOF_DISTORTED_KILLING_LEGGINGS.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.MAHORAGA_WHEEL_HELMET.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.MAHORAGA_BODY_HELMET.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.MAHORAGA_BODY_CHESTPLATE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.MAHORAGA_BODY_LEGGINGS.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.COSTUME_TAKABA_HELMET.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.COSTUME_TAKABA_CHESTPLATE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.COSTUME_TAKABA_LEGGINGS.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.COSTUME_TAKABA_BOOTS.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.UNIFORM_HIGURUMA_CHESTPLATE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.UNIFORM_HIGURUMA_LEGGINGS.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_ANGEL_HELMET.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_ANGEL_CHESTPLATE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_REGGIE_STAR_CHESTPLATE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_URO_HELMET.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_URO_CHESTPLATE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_ISHIGORI_HELMET.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_ISHIGORI_CHESTPLATE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_ISHIGORI_LEGGINGS.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_KASHIMO_HAJIME_HELMET.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_KASHIMO_HAJIME_CHESTPLATE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_KASHIMO_HAJIME_LEGGINGS.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_KASHIMO_HAJIME_BOOTS.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_YOROZU_CHESTPLATE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.INSECT_ARMOR_HELMET.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.INSECT_ARMOR_CHESTPLATE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.INSECT_ARMOR_LEGGINGS.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_URAUME_HELMET.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_URAUME_CHESTPLATE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_URAUME_LEGGINGS.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_URAUME_BOOTS.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.CLOTHES_SUKUNA_FUSHIGURO_CHESTPLATE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.SUKUNA_BODY_CHESTPLATE.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.HEAD_JET_HELMET.get());
            tabData.m_246326_((ItemLike)JujutsucraftModItems.HEAD_PROPELLER_HELMET.get());
         }).withTabsBefore(new ResourceLocation[]{JUJUTSUCRAFT_WEAPONS.getId()}).m_257652_());
   }
}
